/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddDnsRecordResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddDnsRecordResponseContent{}

// AddDnsRecordResponseContent struct for AddDnsRecordResponseContent
type AddDnsRecordResponseContent struct {
	Status OperationStatus `json:"status"`
	Data DnsRecordMutationData `json:"data"`
}

type _AddDnsRecordResponseContent AddDnsRecordResponseContent

// NewAddDnsRecordResponseContent instantiates a new AddDnsRecordResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddDnsRecordResponseContent(status OperationStatus, data DnsRecordMutationData) *AddDnsRecordResponseContent {
	this := AddDnsRecordResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewAddDnsRecordResponseContentWithDefaults instantiates a new AddDnsRecordResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddDnsRecordResponseContentWithDefaults() *AddDnsRecordResponseContent {
	this := AddDnsRecordResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *AddDnsRecordResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AddDnsRecordResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AddDnsRecordResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *AddDnsRecordResponseContent) GetData() DnsRecordMutationData {
	if o == nil {
		var ret DnsRecordMutationData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AddDnsRecordResponseContent) GetDataOk() (*DnsRecordMutationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AddDnsRecordResponseContent) SetData(v DnsRecordMutationData) {
	o.Data = v
}

func (o AddDnsRecordResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddDnsRecordResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AddDnsRecordResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddDnsRecordResponseContent := _AddDnsRecordResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddDnsRecordResponseContent)

	if err != nil {
		return err
	}

	*o = AddDnsRecordResponseContent(varAddDnsRecordResponseContent)

	return err
}

type NullableAddDnsRecordResponseContent struct {
	value *AddDnsRecordResponseContent
	isSet bool
}

func (v NullableAddDnsRecordResponseContent) Get() *AddDnsRecordResponseContent {
	return v.value
}

func (v *NullableAddDnsRecordResponseContent) Set(val *AddDnsRecordResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableAddDnsRecordResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableAddDnsRecordResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddDnsRecordResponseContent(val *AddDnsRecordResponseContent) *NullableAddDnsRecordResponseContent {
	return &NullableAddDnsRecordResponseContent{value: val, isSet: true}
}

func (v NullableAddDnsRecordResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddDnsRecordResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


