/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FirewallRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FirewallRule{}

// FirewallRule Firewall rule structure
type FirewallRule struct {
	// SHA1 digest of the rule
	Digest string `json:"digest"`
	// Position/priority of the rule
	Pos int32 `json:"pos"`
	// Rule type (in, out)
	Type string `json:"type"`
	// Action to perform (ACCEPT, REJECT, DROP)
	Action string `json:"action"`
	// Network interface name
	Iface string `json:"iface"`
	// Whether the rule is enabled (1=enabled, 0=disabled)
	Enable int32 `json:"enable"`
	// Comment/description for the rule
	Comment *string `json:"comment,omitempty"`
	// Source address/network
	Source *string `json:"source,omitempty"`
	// Destination address/network
	Dest *string `json:"dest,omitempty"`
	// Protocol (tcp, udp, icmp, etc)
	Proto *string `json:"proto,omitempty"`
	// Destination port
	Dport *string `json:"dport,omitempty"`
	// Source port
	Sport *string `json:"sport,omitempty"`
	// Firewall macro name
	Macro *string `json:"macro,omitempty"`
	// Log level
	Log *string `json:"log,omitempty"`
}

type _FirewallRule FirewallRule

// NewFirewallRule instantiates a new FirewallRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallRule(digest string, pos int32, type_ string, action string, iface string, enable int32) *FirewallRule {
	this := FirewallRule{}
	this.Digest = digest
	this.Pos = pos
	this.Type = type_
	this.Action = action
	this.Iface = iface
	this.Enable = enable
	return &this
}

// NewFirewallRuleWithDefaults instantiates a new FirewallRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallRuleWithDefaults() *FirewallRule {
	this := FirewallRule{}
	return &this
}

// GetDigest returns the Digest field value
func (o *FirewallRule) GetDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Digest
}

// GetDigestOk returns a tuple with the Digest field value
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Digest, true
}

// SetDigest sets field value
func (o *FirewallRule) SetDigest(v string) {
	o.Digest = v
}

// GetPos returns the Pos field value
func (o *FirewallRule) GetPos() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Pos
}

// GetPosOk returns a tuple with the Pos field value
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetPosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pos, true
}

// SetPos sets field value
func (o *FirewallRule) SetPos(v int32) {
	o.Pos = v
}

// GetType returns the Type field value
func (o *FirewallRule) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FirewallRule) SetType(v string) {
	o.Type = v
}

// GetAction returns the Action field value
func (o *FirewallRule) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *FirewallRule) SetAction(v string) {
	o.Action = v
}

// GetIface returns the Iface field value
func (o *FirewallRule) GetIface() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Iface
}

// GetIfaceOk returns a tuple with the Iface field value
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetIfaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Iface, true
}

// SetIface sets field value
func (o *FirewallRule) SetIface(v string) {
	o.Iface = v
}

// GetEnable returns the Enable field value
func (o *FirewallRule) GetEnable() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Enable
}

// GetEnableOk returns a tuple with the Enable field value
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetEnableOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enable, true
}

// SetEnable sets field value
func (o *FirewallRule) SetEnable(v int32) {
	o.Enable = v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *FirewallRule) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *FirewallRule) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *FirewallRule) SetComment(v string) {
	o.Comment = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *FirewallRule) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *FirewallRule) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *FirewallRule) SetSource(v string) {
	o.Source = &v
}

// GetDest returns the Dest field value if set, zero value otherwise.
func (o *FirewallRule) GetDest() string {
	if o == nil || IsNil(o.Dest) {
		var ret string
		return ret
	}
	return *o.Dest
}

// GetDestOk returns a tuple with the Dest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetDestOk() (*string, bool) {
	if o == nil || IsNil(o.Dest) {
		return nil, false
	}
	return o.Dest, true
}

// HasDest returns a boolean if a field has been set.
func (o *FirewallRule) HasDest() bool {
	if o != nil && !IsNil(o.Dest) {
		return true
	}

	return false
}

// SetDest gets a reference to the given string and assigns it to the Dest field.
func (o *FirewallRule) SetDest(v string) {
	o.Dest = &v
}

// GetProto returns the Proto field value if set, zero value otherwise.
func (o *FirewallRule) GetProto() string {
	if o == nil || IsNil(o.Proto) {
		var ret string
		return ret
	}
	return *o.Proto
}

// GetProtoOk returns a tuple with the Proto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetProtoOk() (*string, bool) {
	if o == nil || IsNil(o.Proto) {
		return nil, false
	}
	return o.Proto, true
}

// HasProto returns a boolean if a field has been set.
func (o *FirewallRule) HasProto() bool {
	if o != nil && !IsNil(o.Proto) {
		return true
	}

	return false
}

// SetProto gets a reference to the given string and assigns it to the Proto field.
func (o *FirewallRule) SetProto(v string) {
	o.Proto = &v
}

// GetDport returns the Dport field value if set, zero value otherwise.
func (o *FirewallRule) GetDport() string {
	if o == nil || IsNil(o.Dport) {
		var ret string
		return ret
	}
	return *o.Dport
}

// GetDportOk returns a tuple with the Dport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetDportOk() (*string, bool) {
	if o == nil || IsNil(o.Dport) {
		return nil, false
	}
	return o.Dport, true
}

// HasDport returns a boolean if a field has been set.
func (o *FirewallRule) HasDport() bool {
	if o != nil && !IsNil(o.Dport) {
		return true
	}

	return false
}

// SetDport gets a reference to the given string and assigns it to the Dport field.
func (o *FirewallRule) SetDport(v string) {
	o.Dport = &v
}

// GetSport returns the Sport field value if set, zero value otherwise.
func (o *FirewallRule) GetSport() string {
	if o == nil || IsNil(o.Sport) {
		var ret string
		return ret
	}
	return *o.Sport
}

// GetSportOk returns a tuple with the Sport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetSportOk() (*string, bool) {
	if o == nil || IsNil(o.Sport) {
		return nil, false
	}
	return o.Sport, true
}

// HasSport returns a boolean if a field has been set.
func (o *FirewallRule) HasSport() bool {
	if o != nil && !IsNil(o.Sport) {
		return true
	}

	return false
}

// SetSport gets a reference to the given string and assigns it to the Sport field.
func (o *FirewallRule) SetSport(v string) {
	o.Sport = &v
}

// GetMacro returns the Macro field value if set, zero value otherwise.
func (o *FirewallRule) GetMacro() string {
	if o == nil || IsNil(o.Macro) {
		var ret string
		return ret
	}
	return *o.Macro
}

// GetMacroOk returns a tuple with the Macro field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetMacroOk() (*string, bool) {
	if o == nil || IsNil(o.Macro) {
		return nil, false
	}
	return o.Macro, true
}

// HasMacro returns a boolean if a field has been set.
func (o *FirewallRule) HasMacro() bool {
	if o != nil && !IsNil(o.Macro) {
		return true
	}

	return false
}

// SetMacro gets a reference to the given string and assigns it to the Macro field.
func (o *FirewallRule) SetMacro(v string) {
	o.Macro = &v
}

// GetLog returns the Log field value if set, zero value otherwise.
func (o *FirewallRule) GetLog() string {
	if o == nil || IsNil(o.Log) {
		var ret string
		return ret
	}
	return *o.Log
}

// GetLogOk returns a tuple with the Log field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRule) GetLogOk() (*string, bool) {
	if o == nil || IsNil(o.Log) {
		return nil, false
	}
	return o.Log, true
}

// HasLog returns a boolean if a field has been set.
func (o *FirewallRule) HasLog() bool {
	if o != nil && !IsNil(o.Log) {
		return true
	}

	return false
}

// SetLog gets a reference to the given string and assigns it to the Log field.
func (o *FirewallRule) SetLog(v string) {
	o.Log = &v
}

func (o FirewallRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FirewallRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["digest"] = o.Digest
	toSerialize["pos"] = o.Pos
	toSerialize["type"] = o.Type
	toSerialize["action"] = o.Action
	toSerialize["iface"] = o.Iface
	toSerialize["enable"] = o.Enable
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Dest) {
		toSerialize["dest"] = o.Dest
	}
	if !IsNil(o.Proto) {
		toSerialize["proto"] = o.Proto
	}
	if !IsNil(o.Dport) {
		toSerialize["dport"] = o.Dport
	}
	if !IsNil(o.Sport) {
		toSerialize["sport"] = o.Sport
	}
	if !IsNil(o.Macro) {
		toSerialize["macro"] = o.Macro
	}
	if !IsNil(o.Log) {
		toSerialize["log"] = o.Log
	}
	return toSerialize, nil
}

func (o *FirewallRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"digest",
		"pos",
		"type",
		"action",
		"iface",
		"enable",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFirewallRule := _FirewallRule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFirewallRule)

	if err != nil {
		return err
	}

	*o = FirewallRule(varFirewallRule)

	return err
}

type NullableFirewallRule struct {
	value *FirewallRule
	isSet bool
}

func (v NullableFirewallRule) Get() *FirewallRule {
	return v.value
}

func (v *NullableFirewallRule) Set(val *FirewallRule) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallRule) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallRule(val *FirewallRule) *NullableFirewallRule {
	return &NullableFirewallRule{value: val, isSet: true}
}

func (v NullableFirewallRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


