/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateNotificationResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNotificationResponseContent{}

// CreateNotificationResponseContent struct for CreateNotificationResponseContent
type CreateNotificationResponseContent struct {
	Status OperationStatus `json:"status"`
	Data NotificationCreateResponseData `json:"data"`
}

type _CreateNotificationResponseContent CreateNotificationResponseContent

// NewCreateNotificationResponseContent instantiates a new CreateNotificationResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNotificationResponseContent(status OperationStatus, data NotificationCreateResponseData) *CreateNotificationResponseContent {
	this := CreateNotificationResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewCreateNotificationResponseContentWithDefaults instantiates a new CreateNotificationResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNotificationResponseContentWithDefaults() *CreateNotificationResponseContent {
	this := CreateNotificationResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *CreateNotificationResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateNotificationResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *CreateNotificationResponseContent) GetData() NotificationCreateResponseData {
	if o == nil {
		var ret NotificationCreateResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationResponseContent) GetDataOk() (*NotificationCreateResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateNotificationResponseContent) SetData(v NotificationCreateResponseData) {
	o.Data = v
}

func (o CreateNotificationResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNotificationResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateNotificationResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateNotificationResponseContent := _CreateNotificationResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateNotificationResponseContent)

	if err != nil {
		return err
	}

	*o = CreateNotificationResponseContent(varCreateNotificationResponseContent)

	return err
}

type NullableCreateNotificationResponseContent struct {
	value *CreateNotificationResponseContent
	isSet bool
}

func (v NullableCreateNotificationResponseContent) Get() *CreateNotificationResponseContent {
	return v.value
}

func (v *NullableCreateNotificationResponseContent) Set(val *CreateNotificationResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNotificationResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNotificationResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNotificationResponseContent(val *CreateNotificationResponseContent) *NullableCreateNotificationResponseContent {
	return &NullableCreateNotificationResponseContent{value: val, isSet: true}
}

func (v NullableCreateNotificationResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNotificationResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


