/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListDnsTemplatesResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDnsTemplatesResponseContent{}

// ListDnsTemplatesResponseContent struct for ListDnsTemplatesResponseContent
type ListDnsTemplatesResponseContent struct {
	Status OperationStatus `json:"status"`
	Data ListDnsTemplatesData `json:"data"`
}

type _ListDnsTemplatesResponseContent ListDnsTemplatesResponseContent

// NewListDnsTemplatesResponseContent instantiates a new ListDnsTemplatesResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDnsTemplatesResponseContent(status OperationStatus, data ListDnsTemplatesData) *ListDnsTemplatesResponseContent {
	this := ListDnsTemplatesResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewListDnsTemplatesResponseContentWithDefaults instantiates a new ListDnsTemplatesResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDnsTemplatesResponseContentWithDefaults() *ListDnsTemplatesResponseContent {
	this := ListDnsTemplatesResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *ListDnsTemplatesResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ListDnsTemplatesResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ListDnsTemplatesResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *ListDnsTemplatesResponseContent) GetData() ListDnsTemplatesData {
	if o == nil {
		var ret ListDnsTemplatesData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListDnsTemplatesResponseContent) GetDataOk() (*ListDnsTemplatesData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ListDnsTemplatesResponseContent) SetData(v ListDnsTemplatesData) {
	o.Data = v
}

func (o ListDnsTemplatesResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDnsTemplatesResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ListDnsTemplatesResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListDnsTemplatesResponseContent := _ListDnsTemplatesResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListDnsTemplatesResponseContent)

	if err != nil {
		return err
	}

	*o = ListDnsTemplatesResponseContent(varListDnsTemplatesResponseContent)

	return err
}

type NullableListDnsTemplatesResponseContent struct {
	value *ListDnsTemplatesResponseContent
	isSet bool
}

func (v NullableListDnsTemplatesResponseContent) Get() *ListDnsTemplatesResponseContent {
	return v.value
}

func (v *NullableListDnsTemplatesResponseContent) Set(val *ListDnsTemplatesResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableListDnsTemplatesResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableListDnsTemplatesResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDnsTemplatesResponseContent(val *ListDnsTemplatesResponseContent) *NullableListDnsTemplatesResponseContent {
	return &NullableListDnsTemplatesResponseContent{value: val, isSet: true}
}

func (v NullableListDnsTemplatesResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDnsTemplatesResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


