/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BadRequestErrorResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BadRequestErrorResponseContent{}

// BadRequestErrorResponseContent struct for BadRequestErrorResponseContent
type BadRequestErrorResponseContent struct {
	Message string `json:"message"`
	// Empty object for operations that don't return data
	Data map[string]interface{} `json:"data"`
}

type _BadRequestErrorResponseContent BadRequestErrorResponseContent

// NewBadRequestErrorResponseContent instantiates a new BadRequestErrorResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBadRequestErrorResponseContent(message string, data map[string]interface{}) *BadRequestErrorResponseContent {
	this := BadRequestErrorResponseContent{}
	this.Message = message
	this.Data = data
	return &this
}

// NewBadRequestErrorResponseContentWithDefaults instantiates a new BadRequestErrorResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBadRequestErrorResponseContentWithDefaults() *BadRequestErrorResponseContent {
	this := BadRequestErrorResponseContent{}
	return &this
}

// GetMessage returns the Message field value
func (o *BadRequestErrorResponseContent) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *BadRequestErrorResponseContent) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *BadRequestErrorResponseContent) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *BadRequestErrorResponseContent) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BadRequestErrorResponseContent) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BadRequestErrorResponseContent) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o BadRequestErrorResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BadRequestErrorResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *BadRequestErrorResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBadRequestErrorResponseContent := _BadRequestErrorResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBadRequestErrorResponseContent)

	if err != nil {
		return err
	}

	*o = BadRequestErrorResponseContent(varBadRequestErrorResponseContent)

	return err
}

type NullableBadRequestErrorResponseContent struct {
	value *BadRequestErrorResponseContent
	isSet bool
}

func (v NullableBadRequestErrorResponseContent) Get() *BadRequestErrorResponseContent {
	return v.value
}

func (v *NullableBadRequestErrorResponseContent) Set(val *BadRequestErrorResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableBadRequestErrorResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableBadRequestErrorResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBadRequestErrorResponseContent(val *BadRequestErrorResponseContent) *NullableBadRequestErrorResponseContent {
	return &NullableBadRequestErrorResponseContent{value: val, isSet: true}
}

func (v NullableBadRequestErrorResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBadRequestErrorResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


