/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VpsBandwidthInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VpsBandwidthInfo{}

// VpsBandwidthInfo Bandwidth usage information
type VpsBandwidthInfo struct {
	// Bandwidth usage in MB
	UsageMb *float64 `json:"usage_mb,omitempty"`
	// Bandwidth limit in MB
	LimitMb *float64 `json:"limit_mb,omitempty"`
	// Whether bandwidth is unlimited
	Unlimited bool `json:"unlimited"`
	// Bandwidth usage percentage
	Percent *float64 `json:"percent,omitempty"`
}

type _VpsBandwidthInfo VpsBandwidthInfo

// NewVpsBandwidthInfo instantiates a new VpsBandwidthInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVpsBandwidthInfo(unlimited bool) *VpsBandwidthInfo {
	this := VpsBandwidthInfo{}
	this.Unlimited = unlimited
	return &this
}

// NewVpsBandwidthInfoWithDefaults instantiates a new VpsBandwidthInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVpsBandwidthInfoWithDefaults() *VpsBandwidthInfo {
	this := VpsBandwidthInfo{}
	return &this
}

// GetUsageMb returns the UsageMb field value if set, zero value otherwise.
func (o *VpsBandwidthInfo) GetUsageMb() float64 {
	if o == nil || IsNil(o.UsageMb) {
		var ret float64
		return ret
	}
	return *o.UsageMb
}

// GetUsageMbOk returns a tuple with the UsageMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpsBandwidthInfo) GetUsageMbOk() (*float64, bool) {
	if o == nil || IsNil(o.UsageMb) {
		return nil, false
	}
	return o.UsageMb, true
}

// HasUsageMb returns a boolean if a field has been set.
func (o *VpsBandwidthInfo) HasUsageMb() bool {
	if o != nil && !IsNil(o.UsageMb) {
		return true
	}

	return false
}

// SetUsageMb gets a reference to the given float64 and assigns it to the UsageMb field.
func (o *VpsBandwidthInfo) SetUsageMb(v float64) {
	o.UsageMb = &v
}

// GetLimitMb returns the LimitMb field value if set, zero value otherwise.
func (o *VpsBandwidthInfo) GetLimitMb() float64 {
	if o == nil || IsNil(o.LimitMb) {
		var ret float64
		return ret
	}
	return *o.LimitMb
}

// GetLimitMbOk returns a tuple with the LimitMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpsBandwidthInfo) GetLimitMbOk() (*float64, bool) {
	if o == nil || IsNil(o.LimitMb) {
		return nil, false
	}
	return o.LimitMb, true
}

// HasLimitMb returns a boolean if a field has been set.
func (o *VpsBandwidthInfo) HasLimitMb() bool {
	if o != nil && !IsNil(o.LimitMb) {
		return true
	}

	return false
}

// SetLimitMb gets a reference to the given float64 and assigns it to the LimitMb field.
func (o *VpsBandwidthInfo) SetLimitMb(v float64) {
	o.LimitMb = &v
}

// GetUnlimited returns the Unlimited field value
func (o *VpsBandwidthInfo) GetUnlimited() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Unlimited
}

// GetUnlimitedOk returns a tuple with the Unlimited field value
// and a boolean to check if the value has been set.
func (o *VpsBandwidthInfo) GetUnlimitedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unlimited, true
}

// SetUnlimited sets field value
func (o *VpsBandwidthInfo) SetUnlimited(v bool) {
	o.Unlimited = v
}

// GetPercent returns the Percent field value if set, zero value otherwise.
func (o *VpsBandwidthInfo) GetPercent() float64 {
	if o == nil || IsNil(o.Percent) {
		var ret float64
		return ret
	}
	return *o.Percent
}

// GetPercentOk returns a tuple with the Percent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VpsBandwidthInfo) GetPercentOk() (*float64, bool) {
	if o == nil || IsNil(o.Percent) {
		return nil, false
	}
	return o.Percent, true
}

// HasPercent returns a boolean if a field has been set.
func (o *VpsBandwidthInfo) HasPercent() bool {
	if o != nil && !IsNil(o.Percent) {
		return true
	}

	return false
}

// SetPercent gets a reference to the given float64 and assigns it to the Percent field.
func (o *VpsBandwidthInfo) SetPercent(v float64) {
	o.Percent = &v
}

func (o VpsBandwidthInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VpsBandwidthInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UsageMb) {
		toSerialize["usage_mb"] = o.UsageMb
	}
	if !IsNil(o.LimitMb) {
		toSerialize["limit_mb"] = o.LimitMb
	}
	toSerialize["unlimited"] = o.Unlimited
	if !IsNil(o.Percent) {
		toSerialize["percent"] = o.Percent
	}
	return toSerialize, nil
}

func (o *VpsBandwidthInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unlimited",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVpsBandwidthInfo := _VpsBandwidthInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVpsBandwidthInfo)

	if err != nil {
		return err
	}

	*o = VpsBandwidthInfo(varVpsBandwidthInfo)

	return err
}

type NullableVpsBandwidthInfo struct {
	value *VpsBandwidthInfo
	isSet bool
}

func (v NullableVpsBandwidthInfo) Get() *VpsBandwidthInfo {
	return v.value
}

func (v *NullableVpsBandwidthInfo) Set(val *VpsBandwidthInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVpsBandwidthInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVpsBandwidthInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpsBandwidthInfo(val *VpsBandwidthInfo) *NullableVpsBandwidthInfo {
	return &NullableVpsBandwidthInfo{value: val, isSet: true}
}

func (v NullableVpsBandwidthInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpsBandwidthInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


