/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateDomainContactsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDomainContactsData{}

// UpdateDomainContactsData struct for UpdateDomainContactsData
type UpdateDomainContactsData struct {
	// Status message indicating the result
	Message string `json:"message"`
	// Domain service id when returned by upstream
	DomainId *string `json:"domain_id,omitempty"`
}

type _UpdateDomainContactsData UpdateDomainContactsData

// NewUpdateDomainContactsData instantiates a new UpdateDomainContactsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDomainContactsData(message string) *UpdateDomainContactsData {
	this := UpdateDomainContactsData{}
	this.Message = message
	return &this
}

// NewUpdateDomainContactsDataWithDefaults instantiates a new UpdateDomainContactsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDomainContactsDataWithDefaults() *UpdateDomainContactsData {
	this := UpdateDomainContactsData{}
	return &this
}

// GetMessage returns the Message field value
func (o *UpdateDomainContactsData) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *UpdateDomainContactsData) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *UpdateDomainContactsData) SetMessage(v string) {
	o.Message = v
}

// GetDomainId returns the DomainId field value if set, zero value otherwise.
func (o *UpdateDomainContactsData) GetDomainId() string {
	if o == nil || IsNil(o.DomainId) {
		var ret string
		return ret
	}
	return *o.DomainId
}

// GetDomainIdOk returns a tuple with the DomainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDomainContactsData) GetDomainIdOk() (*string, bool) {
	if o == nil || IsNil(o.DomainId) {
		return nil, false
	}
	return o.DomainId, true
}

// HasDomainId returns a boolean if a field has been set.
func (o *UpdateDomainContactsData) HasDomainId() bool {
	if o != nil && !IsNil(o.DomainId) {
		return true
	}

	return false
}

// SetDomainId gets a reference to the given string and assigns it to the DomainId field.
func (o *UpdateDomainContactsData) SetDomainId(v string) {
	o.DomainId = &v
}

func (o UpdateDomainContactsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDomainContactsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	if !IsNil(o.DomainId) {
		toSerialize["domain_id"] = o.DomainId
	}
	return toSerialize, nil
}

func (o *UpdateDomainContactsData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDomainContactsData := _UpdateDomainContactsData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateDomainContactsData)

	if err != nil {
		return err
	}

	*o = UpdateDomainContactsData(varUpdateDomainContactsData)

	return err
}

type NullableUpdateDomainContactsData struct {
	value *UpdateDomainContactsData
	isSet bool
}

func (v NullableUpdateDomainContactsData) Get() *UpdateDomainContactsData {
	return v.value
}

func (v *NullableUpdateDomainContactsData) Set(val *UpdateDomainContactsData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDomainContactsData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDomainContactsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDomainContactsData(val *UpdateDomainContactsData) *NullableUpdateDomainContactsData {
	return &NullableUpdateDomainContactsData{value: val, isSet: true}
}

func (v NullableUpdateDomainContactsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDomainContactsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


