/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateSshKeysResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSshKeysResponseContent{}

// UpdateSshKeysResponseContent struct for UpdateSshKeysResponseContent
type UpdateSshKeysResponseContent struct {
	Status OperationStatus `json:"status"`
	Data VpsSimpleActionResponseData `json:"data"`
}

type _UpdateSshKeysResponseContent UpdateSshKeysResponseContent

// NewUpdateSshKeysResponseContent instantiates a new UpdateSshKeysResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSshKeysResponseContent(status OperationStatus, data VpsSimpleActionResponseData) *UpdateSshKeysResponseContent {
	this := UpdateSshKeysResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewUpdateSshKeysResponseContentWithDefaults instantiates a new UpdateSshKeysResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSshKeysResponseContentWithDefaults() *UpdateSshKeysResponseContent {
	this := UpdateSshKeysResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateSshKeysResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateSshKeysResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateSshKeysResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *UpdateSshKeysResponseContent) GetData() VpsSimpleActionResponseData {
	if o == nil {
		var ret VpsSimpleActionResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateSshKeysResponseContent) GetDataOk() (*VpsSimpleActionResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateSshKeysResponseContent) SetData(v VpsSimpleActionResponseData) {
	o.Data = v
}

func (o UpdateSshKeysResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSshKeysResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateSshKeysResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSshKeysResponseContent := _UpdateSshKeysResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateSshKeysResponseContent)

	if err != nil {
		return err
	}

	*o = UpdateSshKeysResponseContent(varUpdateSshKeysResponseContent)

	return err
}

type NullableUpdateSshKeysResponseContent struct {
	value *UpdateSshKeysResponseContent
	isSet bool
}

func (v NullableUpdateSshKeysResponseContent) Get() *UpdateSshKeysResponseContent {
	return v.value
}

func (v *NullableUpdateSshKeysResponseContent) Set(val *UpdateSshKeysResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSshKeysResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSshKeysResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSshKeysResponseContent(val *UpdateSshKeysResponseContent) *NullableUpdateSshKeysResponseContent {
	return &NullableUpdateSshKeysResponseContent{value: val, isSet: true}
}

func (v NullableUpdateSshKeysResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSshKeysResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


