/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RollbackSnapshotRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RollbackSnapshotRequestContent{}

// RollbackSnapshotRequestContent struct for RollbackSnapshotRequestContent
type RollbackSnapshotRequestContent struct {
	// Service ID - must be sent as a string
	ServiceId string `json:"service_id"`
	// Snapshot name to rollback to
	SnapshotName string `json:"snapshot_name"`
}

type _RollbackSnapshotRequestContent RollbackSnapshotRequestContent

// NewRollbackSnapshotRequestContent instantiates a new RollbackSnapshotRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRollbackSnapshotRequestContent(serviceId string, snapshotName string) *RollbackSnapshotRequestContent {
	this := RollbackSnapshotRequestContent{}
	this.ServiceId = serviceId
	this.SnapshotName = snapshotName
	return &this
}

// NewRollbackSnapshotRequestContentWithDefaults instantiates a new RollbackSnapshotRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRollbackSnapshotRequestContentWithDefaults() *RollbackSnapshotRequestContent {
	this := RollbackSnapshotRequestContent{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *RollbackSnapshotRequestContent) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *RollbackSnapshotRequestContent) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *RollbackSnapshotRequestContent) SetServiceId(v string) {
	o.ServiceId = v
}

// GetSnapshotName returns the SnapshotName field value
func (o *RollbackSnapshotRequestContent) GetSnapshotName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SnapshotName
}

// GetSnapshotNameOk returns a tuple with the SnapshotName field value
// and a boolean to check if the value has been set.
func (o *RollbackSnapshotRequestContent) GetSnapshotNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SnapshotName, true
}

// SetSnapshotName sets field value
func (o *RollbackSnapshotRequestContent) SetSnapshotName(v string) {
	o.SnapshotName = v
}

func (o RollbackSnapshotRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RollbackSnapshotRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	toSerialize["snapshot_name"] = o.SnapshotName
	return toSerialize, nil
}

func (o *RollbackSnapshotRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
		"snapshot_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRollbackSnapshotRequestContent := _RollbackSnapshotRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRollbackSnapshotRequestContent)

	if err != nil {
		return err
	}

	*o = RollbackSnapshotRequestContent(varRollbackSnapshotRequestContent)

	return err
}

type NullableRollbackSnapshotRequestContent struct {
	value *RollbackSnapshotRequestContent
	isSet bool
}

func (v NullableRollbackSnapshotRequestContent) Get() *RollbackSnapshotRequestContent {
	return v.value
}

func (v *NullableRollbackSnapshotRequestContent) Set(val *RollbackSnapshotRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableRollbackSnapshotRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableRollbackSnapshotRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRollbackSnapshotRequestContent(val *RollbackSnapshotRequestContent) *NullableRollbackSnapshotRequestContent {
	return &NullableRollbackSnapshotRequestContent{value: val, isSet: true}
}

func (v NullableRollbackSnapshotRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRollbackSnapshotRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


