/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateDomainContactsRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDomainContactsRequestContent{}

// UpdateDomainContactsRequestContent struct for UpdateDomainContactsRequestContent
type UpdateDomainContactsRequestContent struct {
	// Domain service id - must be sent as a string
	DomainId string `json:"domain_id"`
	Contacts DomainContactUpdates `json:"contacts"`
}

type _UpdateDomainContactsRequestContent UpdateDomainContactsRequestContent

// NewUpdateDomainContactsRequestContent instantiates a new UpdateDomainContactsRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDomainContactsRequestContent(domainId string, contacts DomainContactUpdates) *UpdateDomainContactsRequestContent {
	this := UpdateDomainContactsRequestContent{}
	this.DomainId = domainId
	this.Contacts = contacts
	return &this
}

// NewUpdateDomainContactsRequestContentWithDefaults instantiates a new UpdateDomainContactsRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDomainContactsRequestContentWithDefaults() *UpdateDomainContactsRequestContent {
	this := UpdateDomainContactsRequestContent{}
	return &this
}

// GetDomainId returns the DomainId field value
func (o *UpdateDomainContactsRequestContent) GetDomainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DomainId
}

// GetDomainIdOk returns a tuple with the DomainId field value
// and a boolean to check if the value has been set.
func (o *UpdateDomainContactsRequestContent) GetDomainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DomainId, true
}

// SetDomainId sets field value
func (o *UpdateDomainContactsRequestContent) SetDomainId(v string) {
	o.DomainId = v
}

// GetContacts returns the Contacts field value
func (o *UpdateDomainContactsRequestContent) GetContacts() DomainContactUpdates {
	if o == nil {
		var ret DomainContactUpdates
		return ret
	}

	return o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field value
// and a boolean to check if the value has been set.
func (o *UpdateDomainContactsRequestContent) GetContactsOk() (*DomainContactUpdates, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Contacts, true
}

// SetContacts sets field value
func (o *UpdateDomainContactsRequestContent) SetContacts(v DomainContactUpdates) {
	o.Contacts = v
}

func (o UpdateDomainContactsRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDomainContactsRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain_id"] = o.DomainId
	toSerialize["contacts"] = o.Contacts
	return toSerialize, nil
}

func (o *UpdateDomainContactsRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain_id",
		"contacts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDomainContactsRequestContent := _UpdateDomainContactsRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateDomainContactsRequestContent)

	if err != nil {
		return err
	}

	*o = UpdateDomainContactsRequestContent(varUpdateDomainContactsRequestContent)

	return err
}

type NullableUpdateDomainContactsRequestContent struct {
	value *UpdateDomainContactsRequestContent
	isSet bool
}

func (v NullableUpdateDomainContactsRequestContent) Get() *UpdateDomainContactsRequestContent {
	return v.value
}

func (v *NullableUpdateDomainContactsRequestContent) Set(val *UpdateDomainContactsRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDomainContactsRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDomainContactsRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDomainContactsRequestContent(val *UpdateDomainContactsRequestContent) *NullableUpdateDomainContactsRequestContent {
	return &NullableUpdateDomainContactsRequestContent{value: val, isSet: true}
}

func (v NullableUpdateDomainContactsRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDomainContactsRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


