/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValidatePricingProrata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidatePricingProrata{}

// ValidatePricingProrata Prorata charge details for a product
type ValidatePricingProrata struct {
	Applied bool `json:"applied"`
	Amount *string `json:"amount,omitempty"`
	Date *string `json:"date,omitempty"`
	InvoiceDate *string `json:"invoice_date,omitempty"`
	Days *int32 `json:"days,omitempty"`
}

type _ValidatePricingProrata ValidatePricingProrata

// NewValidatePricingProrata instantiates a new ValidatePricingProrata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidatePricingProrata(applied bool) *ValidatePricingProrata {
	this := ValidatePricingProrata{}
	this.Applied = applied
	return &this
}

// NewValidatePricingProrataWithDefaults instantiates a new ValidatePricingProrata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidatePricingProrataWithDefaults() *ValidatePricingProrata {
	this := ValidatePricingProrata{}
	return &this
}

// GetApplied returns the Applied field value
func (o *ValidatePricingProrata) GetApplied() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Applied
}

// GetAppliedOk returns a tuple with the Applied field value
// and a boolean to check if the value has been set.
func (o *ValidatePricingProrata) GetAppliedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Applied, true
}

// SetApplied sets field value
func (o *ValidatePricingProrata) SetApplied(v bool) {
	o.Applied = v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ValidatePricingProrata) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatePricingProrata) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ValidatePricingProrata) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *ValidatePricingProrata) SetAmount(v string) {
	o.Amount = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *ValidatePricingProrata) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatePricingProrata) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *ValidatePricingProrata) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *ValidatePricingProrata) SetDate(v string) {
	o.Date = &v
}

// GetInvoiceDate returns the InvoiceDate field value if set, zero value otherwise.
func (o *ValidatePricingProrata) GetInvoiceDate() string {
	if o == nil || IsNil(o.InvoiceDate) {
		var ret string
		return ret
	}
	return *o.InvoiceDate
}

// GetInvoiceDateOk returns a tuple with the InvoiceDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatePricingProrata) GetInvoiceDateOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceDate) {
		return nil, false
	}
	return o.InvoiceDate, true
}

// HasInvoiceDate returns a boolean if a field has been set.
func (o *ValidatePricingProrata) HasInvoiceDate() bool {
	if o != nil && !IsNil(o.InvoiceDate) {
		return true
	}

	return false
}

// SetInvoiceDate gets a reference to the given string and assigns it to the InvoiceDate field.
func (o *ValidatePricingProrata) SetInvoiceDate(v string) {
	o.InvoiceDate = &v
}

// GetDays returns the Days field value if set, zero value otherwise.
func (o *ValidatePricingProrata) GetDays() int32 {
	if o == nil || IsNil(o.Days) {
		var ret int32
		return ret
	}
	return *o.Days
}

// GetDaysOk returns a tuple with the Days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatePricingProrata) GetDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.Days) {
		return nil, false
	}
	return o.Days, true
}

// HasDays returns a boolean if a field has been set.
func (o *ValidatePricingProrata) HasDays() bool {
	if o != nil && !IsNil(o.Days) {
		return true
	}

	return false
}

// SetDays gets a reference to the given int32 and assigns it to the Days field.
func (o *ValidatePricingProrata) SetDays(v int32) {
	o.Days = &v
}

func (o ValidatePricingProrata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidatePricingProrata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["applied"] = o.Applied
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.InvoiceDate) {
		toSerialize["invoice_date"] = o.InvoiceDate
	}
	if !IsNil(o.Days) {
		toSerialize["days"] = o.Days
	}
	return toSerialize, nil
}

func (o *ValidatePricingProrata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"applied",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidatePricingProrata := _ValidatePricingProrata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidatePricingProrata)

	if err != nil {
		return err
	}

	*o = ValidatePricingProrata(varValidatePricingProrata)

	return err
}

type NullableValidatePricingProrata struct {
	value *ValidatePricingProrata
	isSet bool
}

func (v NullableValidatePricingProrata) Get() *ValidatePricingProrata {
	return v.value
}

func (v *NullableValidatePricingProrata) Set(val *ValidatePricingProrata) {
	v.value = val
	v.isSet = true
}

func (v NullableValidatePricingProrata) IsSet() bool {
	return v.isSet
}

func (v *NullableValidatePricingProrata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidatePricingProrata(val *ValidatePricingProrata) *NullableValidatePricingProrata {
	return &NullableValidatePricingProrata{value: val, isSet: true}
}

func (v NullableValidatePricingProrata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidatePricingProrata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


