/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteDnsRecordResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteDnsRecordResponseContent{}

// DeleteDnsRecordResponseContent struct for DeleteDnsRecordResponseContent
type DeleteDnsRecordResponseContent struct {
	Status OperationStatus `json:"status"`
	Data DnsRecordMutationData `json:"data"`
}

type _DeleteDnsRecordResponseContent DeleteDnsRecordResponseContent

// NewDeleteDnsRecordResponseContent instantiates a new DeleteDnsRecordResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteDnsRecordResponseContent(status OperationStatus, data DnsRecordMutationData) *DeleteDnsRecordResponseContent {
	this := DeleteDnsRecordResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewDeleteDnsRecordResponseContentWithDefaults instantiates a new DeleteDnsRecordResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteDnsRecordResponseContentWithDefaults() *DeleteDnsRecordResponseContent {
	this := DeleteDnsRecordResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *DeleteDnsRecordResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DeleteDnsRecordResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DeleteDnsRecordResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *DeleteDnsRecordResponseContent) GetData() DnsRecordMutationData {
	if o == nil {
		var ret DnsRecordMutationData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteDnsRecordResponseContent) GetDataOk() (*DnsRecordMutationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteDnsRecordResponseContent) SetData(v DnsRecordMutationData) {
	o.Data = v
}

func (o DeleteDnsRecordResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteDnsRecordResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteDnsRecordResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteDnsRecordResponseContent := _DeleteDnsRecordResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteDnsRecordResponseContent)

	if err != nil {
		return err
	}

	*o = DeleteDnsRecordResponseContent(varDeleteDnsRecordResponseContent)

	return err
}

type NullableDeleteDnsRecordResponseContent struct {
	value *DeleteDnsRecordResponseContent
	isSet bool
}

func (v NullableDeleteDnsRecordResponseContent) Get() *DeleteDnsRecordResponseContent {
	return v.value
}

func (v *NullableDeleteDnsRecordResponseContent) Set(val *DeleteDnsRecordResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteDnsRecordResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteDnsRecordResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteDnsRecordResponseContent(val *DeleteDnsRecordResponseContent) *NullableDeleteDnsRecordResponseContent {
	return &NullableDeleteDnsRecordResponseContent{value: val, isSet: true}
}

func (v NullableDeleteDnsRecordResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteDnsRecordResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


