/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ShutdownVpsRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShutdownVpsRequestContent{}

// ShutdownVpsRequestContent struct for ShutdownVpsRequestContent
type ShutdownVpsRequestContent struct {
	// Service ID - must be sent as a string
	ServiceId string `json:"service_id"`
}

type _ShutdownVpsRequestContent ShutdownVpsRequestContent

// NewShutdownVpsRequestContent instantiates a new ShutdownVpsRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShutdownVpsRequestContent(serviceId string) *ShutdownVpsRequestContent {
	this := ShutdownVpsRequestContent{}
	this.ServiceId = serviceId
	return &this
}

// NewShutdownVpsRequestContentWithDefaults instantiates a new ShutdownVpsRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShutdownVpsRequestContentWithDefaults() *ShutdownVpsRequestContent {
	this := ShutdownVpsRequestContent{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *ShutdownVpsRequestContent) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *ShutdownVpsRequestContent) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *ShutdownVpsRequestContent) SetServiceId(v string) {
	o.ServiceId = v
}

func (o ShutdownVpsRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShutdownVpsRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	return toSerialize, nil
}

func (o *ShutdownVpsRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShutdownVpsRequestContent := _ShutdownVpsRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShutdownVpsRequestContent)

	if err != nil {
		return err
	}

	*o = ShutdownVpsRequestContent(varShutdownVpsRequestContent)

	return err
}

type NullableShutdownVpsRequestContent struct {
	value *ShutdownVpsRequestContent
	isSet bool
}

func (v NullableShutdownVpsRequestContent) Get() *ShutdownVpsRequestContent {
	return v.value
}

func (v *NullableShutdownVpsRequestContent) Set(val *ShutdownVpsRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableShutdownVpsRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableShutdownVpsRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShutdownVpsRequestContent(val *ShutdownVpsRequestContent) *NullableShutdownVpsRequestContent {
	return &NullableShutdownVpsRequestContent{value: val, isSet: true}
}

func (v NullableShutdownVpsRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShutdownVpsRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


