/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeletePowerTaskRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletePowerTaskRequestContent{}

// DeletePowerTaskRequestContent struct for DeletePowerTaskRequestContent
type DeletePowerTaskRequestContent struct {
	// Service ID - must be sent as a string
	ServiceId string `json:"service_id"`
	// Power task ID to delete
	TaskId int32 `json:"task_id"`
}

type _DeletePowerTaskRequestContent DeletePowerTaskRequestContent

// NewDeletePowerTaskRequestContent instantiates a new DeletePowerTaskRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletePowerTaskRequestContent(serviceId string, taskId int32) *DeletePowerTaskRequestContent {
	this := DeletePowerTaskRequestContent{}
	this.ServiceId = serviceId
	this.TaskId = taskId
	return &this
}

// NewDeletePowerTaskRequestContentWithDefaults instantiates a new DeletePowerTaskRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletePowerTaskRequestContentWithDefaults() *DeletePowerTaskRequestContent {
	this := DeletePowerTaskRequestContent{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *DeletePowerTaskRequestContent) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *DeletePowerTaskRequestContent) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *DeletePowerTaskRequestContent) SetServiceId(v string) {
	o.ServiceId = v
}

// GetTaskId returns the TaskId field value
func (o *DeletePowerTaskRequestContent) GetTaskId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
func (o *DeletePowerTaskRequestContent) GetTaskIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskId, true
}

// SetTaskId sets field value
func (o *DeletePowerTaskRequestContent) SetTaskId(v int32) {
	o.TaskId = v
}

func (o DeletePowerTaskRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletePowerTaskRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	toSerialize["task_id"] = o.TaskId
	return toSerialize, nil
}

func (o *DeletePowerTaskRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
		"task_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeletePowerTaskRequestContent := _DeletePowerTaskRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeletePowerTaskRequestContent)

	if err != nil {
		return err
	}

	*o = DeletePowerTaskRequestContent(varDeletePowerTaskRequestContent)

	return err
}

type NullableDeletePowerTaskRequestContent struct {
	value *DeletePowerTaskRequestContent
	isSet bool
}

func (v NullableDeletePowerTaskRequestContent) Get() *DeletePowerTaskRequestContent {
	return v.value
}

func (v *NullableDeletePowerTaskRequestContent) Set(val *DeletePowerTaskRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletePowerTaskRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletePowerTaskRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletePowerTaskRequestContent(val *DeletePowerTaskRequestContent) *NullableDeletePowerTaskRequestContent {
	return &NullableDeletePowerTaskRequestContent{value: val, isSet: true}
}

func (v NullableDeletePowerTaskRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletePowerTaskRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


