/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DnssecRecordInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DnssecRecordInfo{}

// DnssecRecordInfo A DNSSEC DS record
type DnssecRecordInfo struct {
	// DNSSEC key tag (0-65535)
	KeyTag int32 `json:"key_tag"`
	// DNSSEC algorithm (1-255)
	Alg int32 `json:"alg"`
	// DNSSEC digest type (1-255)
	DigestType int32 `json:"digest_type"`
	// Hex digest
	Digest string `json:"digest"`
}

type _DnssecRecordInfo DnssecRecordInfo

// NewDnssecRecordInfo instantiates a new DnssecRecordInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnssecRecordInfo(keyTag int32, alg int32, digestType int32, digest string) *DnssecRecordInfo {
	this := DnssecRecordInfo{}
	this.KeyTag = keyTag
	this.Alg = alg
	this.DigestType = digestType
	this.Digest = digest
	return &this
}

// NewDnssecRecordInfoWithDefaults instantiates a new DnssecRecordInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnssecRecordInfoWithDefaults() *DnssecRecordInfo {
	this := DnssecRecordInfo{}
	return &this
}

// GetKeyTag returns the KeyTag field value
func (o *DnssecRecordInfo) GetKeyTag() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.KeyTag
}

// GetKeyTagOk returns a tuple with the KeyTag field value
// and a boolean to check if the value has been set.
func (o *DnssecRecordInfo) GetKeyTagOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyTag, true
}

// SetKeyTag sets field value
func (o *DnssecRecordInfo) SetKeyTag(v int32) {
	o.KeyTag = v
}

// GetAlg returns the Alg field value
func (o *DnssecRecordInfo) GetAlg() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Alg
}

// GetAlgOk returns a tuple with the Alg field value
// and a boolean to check if the value has been set.
func (o *DnssecRecordInfo) GetAlgOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alg, true
}

// SetAlg sets field value
func (o *DnssecRecordInfo) SetAlg(v int32) {
	o.Alg = v
}

// GetDigestType returns the DigestType field value
func (o *DnssecRecordInfo) GetDigestType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DigestType
}

// GetDigestTypeOk returns a tuple with the DigestType field value
// and a boolean to check if the value has been set.
func (o *DnssecRecordInfo) GetDigestTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DigestType, true
}

// SetDigestType sets field value
func (o *DnssecRecordInfo) SetDigestType(v int32) {
	o.DigestType = v
}

// GetDigest returns the Digest field value
func (o *DnssecRecordInfo) GetDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Digest
}

// GetDigestOk returns a tuple with the Digest field value
// and a boolean to check if the value has been set.
func (o *DnssecRecordInfo) GetDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Digest, true
}

// SetDigest sets field value
func (o *DnssecRecordInfo) SetDigest(v string) {
	o.Digest = v
}

func (o DnssecRecordInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DnssecRecordInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key_tag"] = o.KeyTag
	toSerialize["alg"] = o.Alg
	toSerialize["digest_type"] = o.DigestType
	toSerialize["digest"] = o.Digest
	return toSerialize, nil
}

func (o *DnssecRecordInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key_tag",
		"alg",
		"digest_type",
		"digest",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDnssecRecordInfo := _DnssecRecordInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDnssecRecordInfo)

	if err != nil {
		return err
	}

	*o = DnssecRecordInfo(varDnssecRecordInfo)

	return err
}

type NullableDnssecRecordInfo struct {
	value *DnssecRecordInfo
	isSet bool
}

func (v NullableDnssecRecordInfo) Get() *DnssecRecordInfo {
	return v.value
}

func (v *NullableDnssecRecordInfo) Set(val *DnssecRecordInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDnssecRecordInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDnssecRecordInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnssecRecordInfo(val *DnssecRecordInfo) *NullableDnssecRecordInfo {
	return &NullableDnssecRecordInfo{value: val, isSet: true}
}

func (v NullableDnssecRecordInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnssecRecordInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


