/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetPrivateSshKeyResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPrivateSshKeyResponseContent{}

// GetPrivateSshKeyResponseContent struct for GetPrivateSshKeyResponseContent
type GetPrivateSshKeyResponseContent struct {
	Status OperationStatus `json:"status"`
	Data PublicSshKeyResponseData `json:"data"`
}

type _GetPrivateSshKeyResponseContent GetPrivateSshKeyResponseContent

// NewGetPrivateSshKeyResponseContent instantiates a new GetPrivateSshKeyResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPrivateSshKeyResponseContent(status OperationStatus, data PublicSshKeyResponseData) *GetPrivateSshKeyResponseContent {
	this := GetPrivateSshKeyResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewGetPrivateSshKeyResponseContentWithDefaults instantiates a new GetPrivateSshKeyResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPrivateSshKeyResponseContentWithDefaults() *GetPrivateSshKeyResponseContent {
	this := GetPrivateSshKeyResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetPrivateSshKeyResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetPrivateSshKeyResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetPrivateSshKeyResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *GetPrivateSshKeyResponseContent) GetData() PublicSshKeyResponseData {
	if o == nil {
		var ret PublicSshKeyResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetPrivateSshKeyResponseContent) GetDataOk() (*PublicSshKeyResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetPrivateSshKeyResponseContent) SetData(v PublicSshKeyResponseData) {
	o.Data = v
}

func (o GetPrivateSshKeyResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPrivateSshKeyResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetPrivateSshKeyResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetPrivateSshKeyResponseContent := _GetPrivateSshKeyResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetPrivateSshKeyResponseContent)

	if err != nil {
		return err
	}

	*o = GetPrivateSshKeyResponseContent(varGetPrivateSshKeyResponseContent)

	return err
}

type NullableGetPrivateSshKeyResponseContent struct {
	value *GetPrivateSshKeyResponseContent
	isSet bool
}

func (v NullableGetPrivateSshKeyResponseContent) Get() *GetPrivateSshKeyResponseContent {
	return v.value
}

func (v *NullableGetPrivateSshKeyResponseContent) Set(val *GetPrivateSshKeyResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPrivateSshKeyResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPrivateSshKeyResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPrivateSshKeyResponseContent(val *GetPrivateSshKeyResponseContent) *NullableGetPrivateSshKeyResponseContent {
	return &NullableGetPrivateSshKeyResponseContent{value: val, isSet: true}
}

func (v NullableGetPrivateSshKeyResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPrivateSshKeyResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


