/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListDnssecRecordsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDnssecRecordsData{}

// ListDnssecRecordsData struct for ListDnssecRecordsData
type ListDnssecRecordsData struct {
	Message string `json:"message"`
	// DNSSEC DS records configured for the domain
	Records []DnssecRecordInfo `json:"records"`
}

type _ListDnssecRecordsData ListDnssecRecordsData

// NewListDnssecRecordsData instantiates a new ListDnssecRecordsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDnssecRecordsData(message string, records []DnssecRecordInfo) *ListDnssecRecordsData {
	this := ListDnssecRecordsData{}
	this.Message = message
	this.Records = records
	return &this
}

// NewListDnssecRecordsDataWithDefaults instantiates a new ListDnssecRecordsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDnssecRecordsDataWithDefaults() *ListDnssecRecordsData {
	this := ListDnssecRecordsData{}
	return &this
}

// GetMessage returns the Message field value
func (o *ListDnssecRecordsData) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ListDnssecRecordsData) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ListDnssecRecordsData) SetMessage(v string) {
	o.Message = v
}

// GetRecords returns the Records field value
func (o *ListDnssecRecordsData) GetRecords() []DnssecRecordInfo {
	if o == nil {
		var ret []DnssecRecordInfo
		return ret
	}

	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value
// and a boolean to check if the value has been set.
func (o *ListDnssecRecordsData) GetRecordsOk() ([]DnssecRecordInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Records, true
}

// SetRecords sets field value
func (o *ListDnssecRecordsData) SetRecords(v []DnssecRecordInfo) {
	o.Records = v
}

func (o ListDnssecRecordsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDnssecRecordsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["records"] = o.Records
	return toSerialize, nil
}

func (o *ListDnssecRecordsData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"records",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListDnssecRecordsData := _ListDnssecRecordsData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListDnssecRecordsData)

	if err != nil {
		return err
	}

	*o = ListDnssecRecordsData(varListDnssecRecordsData)

	return err
}

type NullableListDnssecRecordsData struct {
	value *ListDnssecRecordsData
	isSet bool
}

func (v NullableListDnssecRecordsData) Get() *ListDnssecRecordsData {
	return v.value
}

func (v *NullableListDnssecRecordsData) Set(val *ListDnssecRecordsData) {
	v.value = val
	v.isSet = true
}

func (v NullableListDnssecRecordsData) IsSet() bool {
	return v.isSet
}

func (v *NullableListDnssecRecordsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDnssecRecordsData(val *ListDnssecRecordsData) *NullableListDnssecRecordsData {
	return &NullableListDnssecRecordsData{value: val, isSet: true}
}

func (v NullableListDnssecRecordsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDnssecRecordsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


