/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NotificationListResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationListResponseData{}

// NotificationListResponseData Response data for listing notifications
type NotificationListResponseData struct {
	// Status message indicating the result
	Message string `json:"message"`
	// List of notifications
	Notifications []Notification `json:"notifications"`
	DialogRules NotificationDialogRules `json:"dialog_rules"`
}

type _NotificationListResponseData NotificationListResponseData

// NewNotificationListResponseData instantiates a new NotificationListResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationListResponseData(message string, notifications []Notification, dialogRules NotificationDialogRules) *NotificationListResponseData {
	this := NotificationListResponseData{}
	this.Message = message
	this.Notifications = notifications
	this.DialogRules = dialogRules
	return &this
}

// NewNotificationListResponseDataWithDefaults instantiates a new NotificationListResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationListResponseDataWithDefaults() *NotificationListResponseData {
	this := NotificationListResponseData{}
	return &this
}

// GetMessage returns the Message field value
func (o *NotificationListResponseData) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *NotificationListResponseData) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *NotificationListResponseData) SetMessage(v string) {
	o.Message = v
}

// GetNotifications returns the Notifications field value
func (o *NotificationListResponseData) GetNotifications() []Notification {
	if o == nil {
		var ret []Notification
		return ret
	}

	return o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value
// and a boolean to check if the value has been set.
func (o *NotificationListResponseData) GetNotificationsOk() ([]Notification, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notifications, true
}

// SetNotifications sets field value
func (o *NotificationListResponseData) SetNotifications(v []Notification) {
	o.Notifications = v
}

// GetDialogRules returns the DialogRules field value
func (o *NotificationListResponseData) GetDialogRules() NotificationDialogRules {
	if o == nil {
		var ret NotificationDialogRules
		return ret
	}

	return o.DialogRules
}

// GetDialogRulesOk returns a tuple with the DialogRules field value
// and a boolean to check if the value has been set.
func (o *NotificationListResponseData) GetDialogRulesOk() (*NotificationDialogRules, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DialogRules, true
}

// SetDialogRules sets field value
func (o *NotificationListResponseData) SetDialogRules(v NotificationDialogRules) {
	o.DialogRules = v
}

func (o NotificationListResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationListResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["notifications"] = o.Notifications
	toSerialize["dialog_rules"] = o.DialogRules
	return toSerialize, nil
}

func (o *NotificationListResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"notifications",
		"dialog_rules",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotificationListResponseData := _NotificationListResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNotificationListResponseData)

	if err != nil {
		return err
	}

	*o = NotificationListResponseData(varNotificationListResponseData)

	return err
}

type NullableNotificationListResponseData struct {
	value *NotificationListResponseData
	isSet bool
}

func (v NullableNotificationListResponseData) Get() *NotificationListResponseData {
	return v.value
}

func (v *NullableNotificationListResponseData) Set(val *NotificationListResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationListResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationListResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationListResponseData(val *NotificationListResponseData) *NullableNotificationListResponseData {
	return &NullableNotificationListResponseData{value: val, isSet: true}
}

func (v NullableNotificationListResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationListResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


