/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateNotificationResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNotificationResponseContent{}

// UpdateNotificationResponseContent struct for UpdateNotificationResponseContent
type UpdateNotificationResponseContent struct {
	Status OperationStatus `json:"status"`
	Data NotificationCreateResponseData `json:"data"`
}

type _UpdateNotificationResponseContent UpdateNotificationResponseContent

// NewUpdateNotificationResponseContent instantiates a new UpdateNotificationResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNotificationResponseContent(status OperationStatus, data NotificationCreateResponseData) *UpdateNotificationResponseContent {
	this := UpdateNotificationResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewUpdateNotificationResponseContentWithDefaults instantiates a new UpdateNotificationResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNotificationResponseContentWithDefaults() *UpdateNotificationResponseContent {
	this := UpdateNotificationResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateNotificationResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateNotificationResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateNotificationResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *UpdateNotificationResponseContent) GetData() NotificationCreateResponseData {
	if o == nil {
		var ret NotificationCreateResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateNotificationResponseContent) GetDataOk() (*NotificationCreateResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateNotificationResponseContent) SetData(v NotificationCreateResponseData) {
	o.Data = v
}

func (o UpdateNotificationResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNotificationResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateNotificationResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateNotificationResponseContent := _UpdateNotificationResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateNotificationResponseContent)

	if err != nil {
		return err
	}

	*o = UpdateNotificationResponseContent(varUpdateNotificationResponseContent)

	return err
}

type NullableUpdateNotificationResponseContent struct {
	value *UpdateNotificationResponseContent
	isSet bool
}

func (v NullableUpdateNotificationResponseContent) Get() *UpdateNotificationResponseContent {
	return v.value
}

func (v *NullableUpdateNotificationResponseContent) Set(val *UpdateNotificationResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNotificationResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNotificationResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNotificationResponseContent(val *UpdateNotificationResponseContent) *NullableUpdateNotificationResponseContent {
	return &NullableUpdateNotificationResponseContent{value: val, isSet: true}
}

func (v NullableUpdateNotificationResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNotificationResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


