/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListIsosResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListIsosResponseData{}

// ListIsosResponseData Response data for list ISOs operation
type ListIsosResponseData struct {
	// Status message indicating the result
	Message string `json:"message"`
	// List of available ISO images
	Isos []string `json:"isos"`
}

type _ListIsosResponseData ListIsosResponseData

// NewListIsosResponseData instantiates a new ListIsosResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListIsosResponseData(message string, isos []string) *ListIsosResponseData {
	this := ListIsosResponseData{}
	this.Message = message
	this.Isos = isos
	return &this
}

// NewListIsosResponseDataWithDefaults instantiates a new ListIsosResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListIsosResponseDataWithDefaults() *ListIsosResponseData {
	this := ListIsosResponseData{}
	return &this
}

// GetMessage returns the Message field value
func (o *ListIsosResponseData) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ListIsosResponseData) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ListIsosResponseData) SetMessage(v string) {
	o.Message = v
}

// GetIsos returns the Isos field value
func (o *ListIsosResponseData) GetIsos() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Isos
}

// GetIsosOk returns a tuple with the Isos field value
// and a boolean to check if the value has been set.
func (o *ListIsosResponseData) GetIsosOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Isos, true
}

// SetIsos sets field value
func (o *ListIsosResponseData) SetIsos(v []string) {
	o.Isos = v
}

func (o ListIsosResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListIsosResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["isos"] = o.Isos
	return toSerialize, nil
}

func (o *ListIsosResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"isos",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListIsosResponseData := _ListIsosResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListIsosResponseData)

	if err != nil {
		return err
	}

	*o = ListIsosResponseData(varListIsosResponseData)

	return err
}

type NullableListIsosResponseData struct {
	value *ListIsosResponseData
	isSet bool
}

func (v NullableListIsosResponseData) Get() *ListIsosResponseData {
	return v.value
}

func (v *NullableListIsosResponseData) Set(val *ListIsosResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableListIsosResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableListIsosResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListIsosResponseData(val *ListIsosResponseData) *NullableListIsosResponseData {
	return &NullableListIsosResponseData{value: val, isSet: true}
}

func (v NullableListIsosResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListIsosResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


