/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SnapshotJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnapshotJob{}

// SnapshotJob Individual snapshot job item
type SnapshotJob struct {
	// Snapshot job ID
	Id int32 `json:"id"`
	// Hosting account ID
	HostingId *int32 `json:"hosting_id,omitempty"`
	// VM ID (null if not yet assigned)
	VmId *int32 `json:"vm_id,omitempty"`
	// Name of the snapshot job
	Name string `json:"name"`
	// Description of the snapshot job
	Description *string `json:"description,omitempty"`
	// Whether VM state is included in the snapshot
	Vmstate *bool `json:"vmstate,omitempty"`
	Period SnapshotJobPeriod `json:"period"`
	// For hourly jobs: run every N hours
	RunEvery *int32 `json:"run_every,omitempty"`
	// For daily jobs: days of week
	Days []DayOfWeek `json:"days,omitempty"`
	// For daily jobs: start time in HH:MM format
	StartTime *string `json:"start_time,omitempty"`
}

type _SnapshotJob SnapshotJob

// NewSnapshotJob instantiates a new SnapshotJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnapshotJob(id int32, name string, period SnapshotJobPeriod) *SnapshotJob {
	this := SnapshotJob{}
	this.Id = id
	this.Name = name
	this.Period = period
	return &this
}

// NewSnapshotJobWithDefaults instantiates a new SnapshotJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnapshotJobWithDefaults() *SnapshotJob {
	this := SnapshotJob{}
	return &this
}

// GetId returns the Id field value
func (o *SnapshotJob) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SnapshotJob) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SnapshotJob) SetId(v int32) {
	o.Id = v
}

// GetHostingId returns the HostingId field value if set, zero value otherwise.
func (o *SnapshotJob) GetHostingId() int32 {
	if o == nil || IsNil(o.HostingId) {
		var ret int32
		return ret
	}
	return *o.HostingId
}

// GetHostingIdOk returns a tuple with the HostingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnapshotJob) GetHostingIdOk() (*int32, bool) {
	if o == nil || IsNil(o.HostingId) {
		return nil, false
	}
	return o.HostingId, true
}

// HasHostingId returns a boolean if a field has been set.
func (o *SnapshotJob) HasHostingId() bool {
	if o != nil && !IsNil(o.HostingId) {
		return true
	}

	return false
}

// SetHostingId gets a reference to the given int32 and assigns it to the HostingId field.
func (o *SnapshotJob) SetHostingId(v int32) {
	o.HostingId = &v
}

// GetVmId returns the VmId field value if set, zero value otherwise.
func (o *SnapshotJob) GetVmId() int32 {
	if o == nil || IsNil(o.VmId) {
		var ret int32
		return ret
	}
	return *o.VmId
}

// GetVmIdOk returns a tuple with the VmId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnapshotJob) GetVmIdOk() (*int32, bool) {
	if o == nil || IsNil(o.VmId) {
		return nil, false
	}
	return o.VmId, true
}

// HasVmId returns a boolean if a field has been set.
func (o *SnapshotJob) HasVmId() bool {
	if o != nil && !IsNil(o.VmId) {
		return true
	}

	return false
}

// SetVmId gets a reference to the given int32 and assigns it to the VmId field.
func (o *SnapshotJob) SetVmId(v int32) {
	o.VmId = &v
}

// GetName returns the Name field value
func (o *SnapshotJob) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SnapshotJob) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SnapshotJob) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SnapshotJob) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnapshotJob) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SnapshotJob) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SnapshotJob) SetDescription(v string) {
	o.Description = &v
}

// GetVmstate returns the Vmstate field value if set, zero value otherwise.
func (o *SnapshotJob) GetVmstate() bool {
	if o == nil || IsNil(o.Vmstate) {
		var ret bool
		return ret
	}
	return *o.Vmstate
}

// GetVmstateOk returns a tuple with the Vmstate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnapshotJob) GetVmstateOk() (*bool, bool) {
	if o == nil || IsNil(o.Vmstate) {
		return nil, false
	}
	return o.Vmstate, true
}

// HasVmstate returns a boolean if a field has been set.
func (o *SnapshotJob) HasVmstate() bool {
	if o != nil && !IsNil(o.Vmstate) {
		return true
	}

	return false
}

// SetVmstate gets a reference to the given bool and assigns it to the Vmstate field.
func (o *SnapshotJob) SetVmstate(v bool) {
	o.Vmstate = &v
}

// GetPeriod returns the Period field value
func (o *SnapshotJob) GetPeriod() SnapshotJobPeriod {
	if o == nil {
		var ret SnapshotJobPeriod
		return ret
	}

	return o.Period
}

// GetPeriodOk returns a tuple with the Period field value
// and a boolean to check if the value has been set.
func (o *SnapshotJob) GetPeriodOk() (*SnapshotJobPeriod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Period, true
}

// SetPeriod sets field value
func (o *SnapshotJob) SetPeriod(v SnapshotJobPeriod) {
	o.Period = v
}

// GetRunEvery returns the RunEvery field value if set, zero value otherwise.
func (o *SnapshotJob) GetRunEvery() int32 {
	if o == nil || IsNil(o.RunEvery) {
		var ret int32
		return ret
	}
	return *o.RunEvery
}

// GetRunEveryOk returns a tuple with the RunEvery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnapshotJob) GetRunEveryOk() (*int32, bool) {
	if o == nil || IsNil(o.RunEvery) {
		return nil, false
	}
	return o.RunEvery, true
}

// HasRunEvery returns a boolean if a field has been set.
func (o *SnapshotJob) HasRunEvery() bool {
	if o != nil && !IsNil(o.RunEvery) {
		return true
	}

	return false
}

// SetRunEvery gets a reference to the given int32 and assigns it to the RunEvery field.
func (o *SnapshotJob) SetRunEvery(v int32) {
	o.RunEvery = &v
}

// GetDays returns the Days field value if set, zero value otherwise.
func (o *SnapshotJob) GetDays() []DayOfWeek {
	if o == nil || IsNil(o.Days) {
		var ret []DayOfWeek
		return ret
	}
	return o.Days
}

// GetDaysOk returns a tuple with the Days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnapshotJob) GetDaysOk() ([]DayOfWeek, bool) {
	if o == nil || IsNil(o.Days) {
		return nil, false
	}
	return o.Days, true
}

// HasDays returns a boolean if a field has been set.
func (o *SnapshotJob) HasDays() bool {
	if o != nil && !IsNil(o.Days) {
		return true
	}

	return false
}

// SetDays gets a reference to the given []DayOfWeek and assigns it to the Days field.
func (o *SnapshotJob) SetDays(v []DayOfWeek) {
	o.Days = v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *SnapshotJob) GetStartTime() string {
	if o == nil || IsNil(o.StartTime) {
		var ret string
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnapshotJob) GetStartTimeOk() (*string, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *SnapshotJob) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given string and assigns it to the StartTime field.
func (o *SnapshotJob) SetStartTime(v string) {
	o.StartTime = &v
}

func (o SnapshotJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SnapshotJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.HostingId) {
		toSerialize["hosting_id"] = o.HostingId
	}
	if !IsNil(o.VmId) {
		toSerialize["vm_id"] = o.VmId
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Vmstate) {
		toSerialize["vmstate"] = o.Vmstate
	}
	toSerialize["period"] = o.Period
	if !IsNil(o.RunEvery) {
		toSerialize["run_every"] = o.RunEvery
	}
	if !IsNil(o.Days) {
		toSerialize["days"] = o.Days
	}
	if !IsNil(o.StartTime) {
		toSerialize["start_time"] = o.StartTime
	}
	return toSerialize, nil
}

func (o *SnapshotJob) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"period",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSnapshotJob := _SnapshotJob{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSnapshotJob)

	if err != nil {
		return err
	}

	*o = SnapshotJob(varSnapshotJob)

	return err
}

type NullableSnapshotJob struct {
	value *SnapshotJob
	isSet bool
}

func (v NullableSnapshotJob) Get() *SnapshotJob {
	return v.value
}

func (v *NullableSnapshotJob) Set(val *SnapshotJob) {
	v.value = val
	v.isSet = true
}

func (v NullableSnapshotJob) IsSet() bool {
	return v.isSet
}

func (v *NullableSnapshotJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnapshotJob(val *SnapshotJob) *NullableSnapshotJob {
	return &NullableSnapshotJob{value: val, isSet: true}
}

func (v NullableSnapshotJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnapshotJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


