/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RetryPaymentTotal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetryPaymentTotal{}

// RetryPaymentTotal Total amount breakdown for a retry payment response
type RetryPaymentTotal struct {
	// Total amount charged
	Amount string `json:"amount"`
	// Currency code (e.g. USD)
	Currency string `json:"currency"`
	// Currency prefix symbol (e.g. US$)
	Prefix string `json:"prefix"`
}

type _RetryPaymentTotal RetryPaymentTotal

// NewRetryPaymentTotal instantiates a new RetryPaymentTotal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetryPaymentTotal(amount string, currency string, prefix string) *RetryPaymentTotal {
	this := RetryPaymentTotal{}
	this.Amount = amount
	this.Currency = currency
	this.Prefix = prefix
	return &this
}

// NewRetryPaymentTotalWithDefaults instantiates a new RetryPaymentTotal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetryPaymentTotalWithDefaults() *RetryPaymentTotal {
	this := RetryPaymentTotal{}
	return &this
}

// GetAmount returns the Amount field value
func (o *RetryPaymentTotal) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *RetryPaymentTotal) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *RetryPaymentTotal) SetAmount(v string) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *RetryPaymentTotal) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *RetryPaymentTotal) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *RetryPaymentTotal) SetCurrency(v string) {
	o.Currency = v
}

// GetPrefix returns the Prefix field value
func (o *RetryPaymentTotal) GetPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *RetryPaymentTotal) GetPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *RetryPaymentTotal) SetPrefix(v string) {
	o.Prefix = v
}

func (o RetryPaymentTotal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetryPaymentTotal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["currency"] = o.Currency
	toSerialize["prefix"] = o.Prefix
	return toSerialize, nil
}

func (o *RetryPaymentTotal) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"currency",
		"prefix",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRetryPaymentTotal := _RetryPaymentTotal{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRetryPaymentTotal)

	if err != nil {
		return err
	}

	*o = RetryPaymentTotal(varRetryPaymentTotal)

	return err
}

type NullableRetryPaymentTotal struct {
	value *RetryPaymentTotal
	isSet bool
}

func (v NullableRetryPaymentTotal) Get() *RetryPaymentTotal {
	return v.value
}

func (v *NullableRetryPaymentTotal) Set(val *RetryPaymentTotal) {
	v.value = val
	v.isSet = true
}

func (v NullableRetryPaymentTotal) IsSet() bool {
	return v.isSet
}

func (v *NullableRetryPaymentTotal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetryPaymentTotal(val *RetryPaymentTotal) *NullableRetryPaymentTotal {
	return &NullableRetryPaymentTotal{value: val, isSet: true}
}

func (v NullableRetryPaymentTotal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetryPaymentTotal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


