/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetVpsDetailsRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVpsDetailsRequestContent{}

// GetVpsDetailsRequestContent struct for GetVpsDetailsRequestContent
type GetVpsDetailsRequestContent struct {
	// Service ID - must be sent as a string
	ServiceId string `json:"service_id"`
}

type _GetVpsDetailsRequestContent GetVpsDetailsRequestContent

// NewGetVpsDetailsRequestContent instantiates a new GetVpsDetailsRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVpsDetailsRequestContent(serviceId string) *GetVpsDetailsRequestContent {
	this := GetVpsDetailsRequestContent{}
	this.ServiceId = serviceId
	return &this
}

// NewGetVpsDetailsRequestContentWithDefaults instantiates a new GetVpsDetailsRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVpsDetailsRequestContentWithDefaults() *GetVpsDetailsRequestContent {
	this := GetVpsDetailsRequestContent{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *GetVpsDetailsRequestContent) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *GetVpsDetailsRequestContent) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *GetVpsDetailsRequestContent) SetServiceId(v string) {
	o.ServiceId = v
}

func (o GetVpsDetailsRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVpsDetailsRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	return toSerialize, nil
}

func (o *GetVpsDetailsRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetVpsDetailsRequestContent := _GetVpsDetailsRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetVpsDetailsRequestContent)

	if err != nil {
		return err
	}

	*o = GetVpsDetailsRequestContent(varGetVpsDetailsRequestContent)

	return err
}

type NullableGetVpsDetailsRequestContent struct {
	value *GetVpsDetailsRequestContent
	isSet bool
}

func (v NullableGetVpsDetailsRequestContent) Get() *GetVpsDetailsRequestContent {
	return v.value
}

func (v *NullableGetVpsDetailsRequestContent) Set(val *GetVpsDetailsRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVpsDetailsRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVpsDetailsRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVpsDetailsRequestContent(val *GetVpsDetailsRequestContent) *NullableGetVpsDetailsRequestContent {
	return &NullableGetVpsDetailsRequestContent{value: val, isSet: true}
}

func (v NullableGetVpsDetailsRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVpsDetailsRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


