/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListReinstallOsRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListReinstallOsRequestContent{}

// ListReinstallOsRequestContent struct for ListReinstallOsRequestContent
type ListReinstallOsRequestContent struct {
	// Service ID - must be sent as a string
	ServiceId string `json:"service_id"`
}

type _ListReinstallOsRequestContent ListReinstallOsRequestContent

// NewListReinstallOsRequestContent instantiates a new ListReinstallOsRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListReinstallOsRequestContent(serviceId string) *ListReinstallOsRequestContent {
	this := ListReinstallOsRequestContent{}
	this.ServiceId = serviceId
	return &this
}

// NewListReinstallOsRequestContentWithDefaults instantiates a new ListReinstallOsRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListReinstallOsRequestContentWithDefaults() *ListReinstallOsRequestContent {
	this := ListReinstallOsRequestContent{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *ListReinstallOsRequestContent) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *ListReinstallOsRequestContent) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *ListReinstallOsRequestContent) SetServiceId(v string) {
	o.ServiceId = v
}

func (o ListReinstallOsRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListReinstallOsRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	return toSerialize, nil
}

func (o *ListReinstallOsRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListReinstallOsRequestContent := _ListReinstallOsRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListReinstallOsRequestContent)

	if err != nil {
		return err
	}

	*o = ListReinstallOsRequestContent(varListReinstallOsRequestContent)

	return err
}

type NullableListReinstallOsRequestContent struct {
	value *ListReinstallOsRequestContent
	isSet bool
}

func (v NullableListReinstallOsRequestContent) Get() *ListReinstallOsRequestContent {
	return v.value
}

func (v *NullableListReinstallOsRequestContent) Set(val *ListReinstallOsRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableListReinstallOsRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableListReinstallOsRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListReinstallOsRequestContent(val *ListReinstallOsRequestContent) *NullableListReinstallOsRequestContent {
	return &NullableListReinstallOsRequestContent{value: val, isSet: true}
}

func (v NullableListReinstallOsRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListReinstallOsRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


