/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CancelVpsRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelVpsRequestContent{}

// CancelVpsRequestContent struct for CancelVpsRequestContent
type CancelVpsRequestContent struct {
	// Service ID - must be sent as a string
	ServiceId string `json:"service_id"`
	Type *VpsCancelType `json:"type,omitempty"`
}

type _CancelVpsRequestContent CancelVpsRequestContent

// NewCancelVpsRequestContent instantiates a new CancelVpsRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelVpsRequestContent(serviceId string) *CancelVpsRequestContent {
	this := CancelVpsRequestContent{}
	this.ServiceId = serviceId
	return &this
}

// NewCancelVpsRequestContentWithDefaults instantiates a new CancelVpsRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelVpsRequestContentWithDefaults() *CancelVpsRequestContent {
	this := CancelVpsRequestContent{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *CancelVpsRequestContent) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *CancelVpsRequestContent) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *CancelVpsRequestContent) SetServiceId(v string) {
	o.ServiceId = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CancelVpsRequestContent) GetType() VpsCancelType {
	if o == nil || IsNil(o.Type) {
		var ret VpsCancelType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelVpsRequestContent) GetTypeOk() (*VpsCancelType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CancelVpsRequestContent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given VpsCancelType and assigns it to the Type field.
func (o *CancelVpsRequestContent) SetType(v VpsCancelType) {
	o.Type = &v
}

func (o CancelVpsRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelVpsRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *CancelVpsRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCancelVpsRequestContent := _CancelVpsRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCancelVpsRequestContent)

	if err != nil {
		return err
	}

	*o = CancelVpsRequestContent(varCancelVpsRequestContent)

	return err
}

type NullableCancelVpsRequestContent struct {
	value *CancelVpsRequestContent
	isSet bool
}

func (v NullableCancelVpsRequestContent) Get() *CancelVpsRequestContent {
	return v.value
}

func (v *NullableCancelVpsRequestContent) Set(val *CancelVpsRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelVpsRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelVpsRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelVpsRequestContent(val *CancelVpsRequestContent) *NullableCancelVpsRequestContent {
	return &NullableCancelVpsRequestContent{value: val, isSet: true}
}

func (v NullableCancelVpsRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelVpsRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


