/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteBackupScheduleResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteBackupScheduleResponseContent{}

// DeleteBackupScheduleResponseContent struct for DeleteBackupScheduleResponseContent
type DeleteBackupScheduleResponseContent struct {
	Status OperationStatus `json:"status"`
	Data VpsSimpleActionResponseData `json:"data"`
}

type _DeleteBackupScheduleResponseContent DeleteBackupScheduleResponseContent

// NewDeleteBackupScheduleResponseContent instantiates a new DeleteBackupScheduleResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteBackupScheduleResponseContent(status OperationStatus, data VpsSimpleActionResponseData) *DeleteBackupScheduleResponseContent {
	this := DeleteBackupScheduleResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewDeleteBackupScheduleResponseContentWithDefaults instantiates a new DeleteBackupScheduleResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteBackupScheduleResponseContentWithDefaults() *DeleteBackupScheduleResponseContent {
	this := DeleteBackupScheduleResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *DeleteBackupScheduleResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DeleteBackupScheduleResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DeleteBackupScheduleResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *DeleteBackupScheduleResponseContent) GetData() VpsSimpleActionResponseData {
	if o == nil {
		var ret VpsSimpleActionResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteBackupScheduleResponseContent) GetDataOk() (*VpsSimpleActionResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteBackupScheduleResponseContent) SetData(v VpsSimpleActionResponseData) {
	o.Data = v
}

func (o DeleteBackupScheduleResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteBackupScheduleResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteBackupScheduleResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteBackupScheduleResponseContent := _DeleteBackupScheduleResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteBackupScheduleResponseContent)

	if err != nil {
		return err
	}

	*o = DeleteBackupScheduleResponseContent(varDeleteBackupScheduleResponseContent)

	return err
}

type NullableDeleteBackupScheduleResponseContent struct {
	value *DeleteBackupScheduleResponseContent
	isSet bool
}

func (v NullableDeleteBackupScheduleResponseContent) Get() *DeleteBackupScheduleResponseContent {
	return v.value
}

func (v *NullableDeleteBackupScheduleResponseContent) Set(val *DeleteBackupScheduleResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteBackupScheduleResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteBackupScheduleResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteBackupScheduleResponseContent(val *DeleteBackupScheduleResponseContent) *NullableDeleteBackupScheduleResponseContent {
	return &NullableDeleteBackupScheduleResponseContent{value: val, isSet: true}
}

func (v NullableDeleteBackupScheduleResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteBackupScheduleResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


