/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOrderRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrderRequestContent{}

// CreateOrderRequestContent struct for CreateOrderRequestContent
type CreateOrderRequestContent struct {
	// Promotional code to apply to the order
	Promo *string `json:"promo,omitempty"`
	// List of products to order
	Products []CreateOrderProduct `json:"products"`
}

type _CreateOrderRequestContent CreateOrderRequestContent

// NewCreateOrderRequestContent instantiates a new CreateOrderRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestContent(products []CreateOrderProduct) *CreateOrderRequestContent {
	this := CreateOrderRequestContent{}
	this.Products = products
	return &this
}

// NewCreateOrderRequestContentWithDefaults instantiates a new CreateOrderRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestContentWithDefaults() *CreateOrderRequestContent {
	this := CreateOrderRequestContent{}
	return &this
}

// GetPromo returns the Promo field value if set, zero value otherwise.
func (o *CreateOrderRequestContent) GetPromo() string {
	if o == nil || IsNil(o.Promo) {
		var ret string
		return ret
	}
	return *o.Promo
}

// GetPromoOk returns a tuple with the Promo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestContent) GetPromoOk() (*string, bool) {
	if o == nil || IsNil(o.Promo) {
		return nil, false
	}
	return o.Promo, true
}

// HasPromo returns a boolean if a field has been set.
func (o *CreateOrderRequestContent) HasPromo() bool {
	if o != nil && !IsNil(o.Promo) {
		return true
	}

	return false
}

// SetPromo gets a reference to the given string and assigns it to the Promo field.
func (o *CreateOrderRequestContent) SetPromo(v string) {
	o.Promo = &v
}

// GetProducts returns the Products field value
func (o *CreateOrderRequestContent) GetProducts() []CreateOrderProduct {
	if o == nil {
		var ret []CreateOrderProduct
		return ret
	}

	return o.Products
}

// GetProductsOk returns a tuple with the Products field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestContent) GetProductsOk() ([]CreateOrderProduct, bool) {
	if o == nil {
		return nil, false
	}
	return o.Products, true
}

// SetProducts sets field value
func (o *CreateOrderRequestContent) SetProducts(v []CreateOrderProduct) {
	o.Products = v
}

func (o CreateOrderRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrderRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Promo) {
		toSerialize["promo"] = o.Promo
	}
	toSerialize["products"] = o.Products
	return toSerialize, nil
}

func (o *CreateOrderRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"products",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrderRequestContent := _CreateOrderRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrderRequestContent)

	if err != nil {
		return err
	}

	*o = CreateOrderRequestContent(varCreateOrderRequestContent)

	return err
}

type NullableCreateOrderRequestContent struct {
	value *CreateOrderRequestContent
	isSet bool
}

func (v NullableCreateOrderRequestContent) Get() *CreateOrderRequestContent {
	return v.value
}

func (v *NullableCreateOrderRequestContent) Set(val *CreateOrderRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestContent(val *CreateOrderRequestContent) *NullableCreateOrderRequestContent {
	return &NullableCreateOrderRequestContent{value: val, isSet: true}
}

func (v NullableCreateOrderRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


