/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValidatePricingSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidatePricingSummary{}

// ValidatePricingSummary Order-level summary of totals
type ValidatePricingSummary struct {
	Subtotal string `json:"subtotal"`
	DiscountTotal string `json:"discount_total"`
	TotalDue string `json:"total_due"`
	Recurring *ValidatePricingSummaryRecurring `json:"recurring,omitempty"`
	ProrataTotal *string `json:"prorata_total,omitempty"`
	PromoApplied *string `json:"promo_applied,omitempty"`
}

type _ValidatePricingSummary ValidatePricingSummary

// NewValidatePricingSummary instantiates a new ValidatePricingSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidatePricingSummary(subtotal string, discountTotal string, totalDue string) *ValidatePricingSummary {
	this := ValidatePricingSummary{}
	this.Subtotal = subtotal
	this.DiscountTotal = discountTotal
	this.TotalDue = totalDue
	return &this
}

// NewValidatePricingSummaryWithDefaults instantiates a new ValidatePricingSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidatePricingSummaryWithDefaults() *ValidatePricingSummary {
	this := ValidatePricingSummary{}
	return &this
}

// GetSubtotal returns the Subtotal field value
func (o *ValidatePricingSummary) GetSubtotal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subtotal
}

// GetSubtotalOk returns a tuple with the Subtotal field value
// and a boolean to check if the value has been set.
func (o *ValidatePricingSummary) GetSubtotalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subtotal, true
}

// SetSubtotal sets field value
func (o *ValidatePricingSummary) SetSubtotal(v string) {
	o.Subtotal = v
}

// GetDiscountTotal returns the DiscountTotal field value
func (o *ValidatePricingSummary) GetDiscountTotal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DiscountTotal
}

// GetDiscountTotalOk returns a tuple with the DiscountTotal field value
// and a boolean to check if the value has been set.
func (o *ValidatePricingSummary) GetDiscountTotalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiscountTotal, true
}

// SetDiscountTotal sets field value
func (o *ValidatePricingSummary) SetDiscountTotal(v string) {
	o.DiscountTotal = v
}

// GetTotalDue returns the TotalDue field value
func (o *ValidatePricingSummary) GetTotalDue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TotalDue
}

// GetTotalDueOk returns a tuple with the TotalDue field value
// and a boolean to check if the value has been set.
func (o *ValidatePricingSummary) GetTotalDueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalDue, true
}

// SetTotalDue sets field value
func (o *ValidatePricingSummary) SetTotalDue(v string) {
	o.TotalDue = v
}

// GetRecurring returns the Recurring field value if set, zero value otherwise.
func (o *ValidatePricingSummary) GetRecurring() ValidatePricingSummaryRecurring {
	if o == nil || IsNil(o.Recurring) {
		var ret ValidatePricingSummaryRecurring
		return ret
	}
	return *o.Recurring
}

// GetRecurringOk returns a tuple with the Recurring field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatePricingSummary) GetRecurringOk() (*ValidatePricingSummaryRecurring, bool) {
	if o == nil || IsNil(o.Recurring) {
		return nil, false
	}
	return o.Recurring, true
}

// HasRecurring returns a boolean if a field has been set.
func (o *ValidatePricingSummary) HasRecurring() bool {
	if o != nil && !IsNil(o.Recurring) {
		return true
	}

	return false
}

// SetRecurring gets a reference to the given ValidatePricingSummaryRecurring and assigns it to the Recurring field.
func (o *ValidatePricingSummary) SetRecurring(v ValidatePricingSummaryRecurring) {
	o.Recurring = &v
}

// GetProrataTotal returns the ProrataTotal field value if set, zero value otherwise.
func (o *ValidatePricingSummary) GetProrataTotal() string {
	if o == nil || IsNil(o.ProrataTotal) {
		var ret string
		return ret
	}
	return *o.ProrataTotal
}

// GetProrataTotalOk returns a tuple with the ProrataTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatePricingSummary) GetProrataTotalOk() (*string, bool) {
	if o == nil || IsNil(o.ProrataTotal) {
		return nil, false
	}
	return o.ProrataTotal, true
}

// HasProrataTotal returns a boolean if a field has been set.
func (o *ValidatePricingSummary) HasProrataTotal() bool {
	if o != nil && !IsNil(o.ProrataTotal) {
		return true
	}

	return false
}

// SetProrataTotal gets a reference to the given string and assigns it to the ProrataTotal field.
func (o *ValidatePricingSummary) SetProrataTotal(v string) {
	o.ProrataTotal = &v
}

// GetPromoApplied returns the PromoApplied field value if set, zero value otherwise.
func (o *ValidatePricingSummary) GetPromoApplied() string {
	if o == nil || IsNil(o.PromoApplied) {
		var ret string
		return ret
	}
	return *o.PromoApplied
}

// GetPromoAppliedOk returns a tuple with the PromoApplied field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatePricingSummary) GetPromoAppliedOk() (*string, bool) {
	if o == nil || IsNil(o.PromoApplied) {
		return nil, false
	}
	return o.PromoApplied, true
}

// HasPromoApplied returns a boolean if a field has been set.
func (o *ValidatePricingSummary) HasPromoApplied() bool {
	if o != nil && !IsNil(o.PromoApplied) {
		return true
	}

	return false
}

// SetPromoApplied gets a reference to the given string and assigns it to the PromoApplied field.
func (o *ValidatePricingSummary) SetPromoApplied(v string) {
	o.PromoApplied = &v
}

func (o ValidatePricingSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidatePricingSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subtotal"] = o.Subtotal
	toSerialize["discount_total"] = o.DiscountTotal
	toSerialize["total_due"] = o.TotalDue
	if !IsNil(o.Recurring) {
		toSerialize["recurring"] = o.Recurring
	}
	if !IsNil(o.ProrataTotal) {
		toSerialize["prorata_total"] = o.ProrataTotal
	}
	if !IsNil(o.PromoApplied) {
		toSerialize["promo_applied"] = o.PromoApplied
	}
	return toSerialize, nil
}

func (o *ValidatePricingSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subtotal",
		"discount_total",
		"total_due",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidatePricingSummary := _ValidatePricingSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidatePricingSummary)

	if err != nil {
		return err
	}

	*o = ValidatePricingSummary(varValidatePricingSummary)

	return err
}

type NullableValidatePricingSummary struct {
	value *ValidatePricingSummary
	isSet bool
}

func (v NullableValidatePricingSummary) Get() *ValidatePricingSummary {
	return v.value
}

func (v *NullableValidatePricingSummary) Set(val *ValidatePricingSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableValidatePricingSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableValidatePricingSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidatePricingSummary(val *ValidatePricingSummary) *NullableValidatePricingSummary {
	return &NullableValidatePricingSummary{value: val, isSet: true}
}

func (v NullableValidatePricingSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidatePricingSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


