/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
)

// checks if the DomainAddons type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainAddons{}

// DomainAddons Optional add-ons available for a domain
type DomainAddons struct {
	Dnsmanagement *bool `json:"dnsmanagement,omitempty"`
	Emailforwarding *bool `json:"emailforwarding,omitempty"`
	Idprotection *bool `json:"idprotection,omitempty"`
}

// NewDomainAddons instantiates a new DomainAddons object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainAddons() *DomainAddons {
	this := DomainAddons{}
	return &this
}

// NewDomainAddonsWithDefaults instantiates a new DomainAddons object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainAddonsWithDefaults() *DomainAddons {
	this := DomainAddons{}
	return &this
}

// GetDnsmanagement returns the Dnsmanagement field value if set, zero value otherwise.
func (o *DomainAddons) GetDnsmanagement() bool {
	if o == nil || IsNil(o.Dnsmanagement) {
		var ret bool
		return ret
	}
	return *o.Dnsmanagement
}

// GetDnsmanagementOk returns a tuple with the Dnsmanagement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainAddons) GetDnsmanagementOk() (*bool, bool) {
	if o == nil || IsNil(o.Dnsmanagement) {
		return nil, false
	}
	return o.Dnsmanagement, true
}

// HasDnsmanagement returns a boolean if a field has been set.
func (o *DomainAddons) HasDnsmanagement() bool {
	if o != nil && !IsNil(o.Dnsmanagement) {
		return true
	}

	return false
}

// SetDnsmanagement gets a reference to the given bool and assigns it to the Dnsmanagement field.
func (o *DomainAddons) SetDnsmanagement(v bool) {
	o.Dnsmanagement = &v
}

// GetEmailforwarding returns the Emailforwarding field value if set, zero value otherwise.
func (o *DomainAddons) GetEmailforwarding() bool {
	if o == nil || IsNil(o.Emailforwarding) {
		var ret bool
		return ret
	}
	return *o.Emailforwarding
}

// GetEmailforwardingOk returns a tuple with the Emailforwarding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainAddons) GetEmailforwardingOk() (*bool, bool) {
	if o == nil || IsNil(o.Emailforwarding) {
		return nil, false
	}
	return o.Emailforwarding, true
}

// HasEmailforwarding returns a boolean if a field has been set.
func (o *DomainAddons) HasEmailforwarding() bool {
	if o != nil && !IsNil(o.Emailforwarding) {
		return true
	}

	return false
}

// SetEmailforwarding gets a reference to the given bool and assigns it to the Emailforwarding field.
func (o *DomainAddons) SetEmailforwarding(v bool) {
	o.Emailforwarding = &v
}

// GetIdprotection returns the Idprotection field value if set, zero value otherwise.
func (o *DomainAddons) GetIdprotection() bool {
	if o == nil || IsNil(o.Idprotection) {
		var ret bool
		return ret
	}
	return *o.Idprotection
}

// GetIdprotectionOk returns a tuple with the Idprotection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainAddons) GetIdprotectionOk() (*bool, bool) {
	if o == nil || IsNil(o.Idprotection) {
		return nil, false
	}
	return o.Idprotection, true
}

// HasIdprotection returns a boolean if a field has been set.
func (o *DomainAddons) HasIdprotection() bool {
	if o != nil && !IsNil(o.Idprotection) {
		return true
	}

	return false
}

// SetIdprotection gets a reference to the given bool and assigns it to the Idprotection field.
func (o *DomainAddons) SetIdprotection(v bool) {
	o.Idprotection = &v
}

func (o DomainAddons) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainAddons) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dnsmanagement) {
		toSerialize["dnsmanagement"] = o.Dnsmanagement
	}
	if !IsNil(o.Emailforwarding) {
		toSerialize["emailforwarding"] = o.Emailforwarding
	}
	if !IsNil(o.Idprotection) {
		toSerialize["idprotection"] = o.Idprotection
	}
	return toSerialize, nil
}

type NullableDomainAddons struct {
	value *DomainAddons
	isSet bool
}

func (v NullableDomainAddons) Get() *DomainAddons {
	return v.value
}

func (v *NullableDomainAddons) Set(val *DomainAddons) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainAddons) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainAddons) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainAddons(val *DomainAddons) *NullableDomainAddons {
	return &NullableDomainAddons{value: val, isSet: true}
}

func (v NullableDomainAddons) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainAddons) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


