/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TooManyRequestsErrorResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TooManyRequestsErrorResponseContent{}

// TooManyRequestsErrorResponseContent struct for TooManyRequestsErrorResponseContent
type TooManyRequestsErrorResponseContent struct {
	Message string `json:"message"`
	// Empty object for operations that don't return data
	Data map[string]interface{} `json:"data"`
}

type _TooManyRequestsErrorResponseContent TooManyRequestsErrorResponseContent

// NewTooManyRequestsErrorResponseContent instantiates a new TooManyRequestsErrorResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTooManyRequestsErrorResponseContent(message string, data map[string]interface{}) *TooManyRequestsErrorResponseContent {
	this := TooManyRequestsErrorResponseContent{}
	this.Message = message
	this.Data = data
	return &this
}

// NewTooManyRequestsErrorResponseContentWithDefaults instantiates a new TooManyRequestsErrorResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTooManyRequestsErrorResponseContentWithDefaults() *TooManyRequestsErrorResponseContent {
	this := TooManyRequestsErrorResponseContent{}
	return &this
}

// GetMessage returns the Message field value
func (o *TooManyRequestsErrorResponseContent) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *TooManyRequestsErrorResponseContent) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *TooManyRequestsErrorResponseContent) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *TooManyRequestsErrorResponseContent) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TooManyRequestsErrorResponseContent) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *TooManyRequestsErrorResponseContent) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o TooManyRequestsErrorResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TooManyRequestsErrorResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *TooManyRequestsErrorResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTooManyRequestsErrorResponseContent := _TooManyRequestsErrorResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTooManyRequestsErrorResponseContent)

	if err != nil {
		return err
	}

	*o = TooManyRequestsErrorResponseContent(varTooManyRequestsErrorResponseContent)

	return err
}

type NullableTooManyRequestsErrorResponseContent struct {
	value *TooManyRequestsErrorResponseContent
	isSet bool
}

func (v NullableTooManyRequestsErrorResponseContent) Get() *TooManyRequestsErrorResponseContent {
	return v.value
}

func (v *NullableTooManyRequestsErrorResponseContent) Set(val *TooManyRequestsErrorResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableTooManyRequestsErrorResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableTooManyRequestsErrorResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTooManyRequestsErrorResponseContent(val *TooManyRequestsErrorResponseContent) *NullableTooManyRequestsErrorResponseContent {
	return &NullableTooManyRequestsErrorResponseContent{value: val, isSet: true}
}

func (v NullableTooManyRequestsErrorResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTooManyRequestsErrorResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


