/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateNotificationRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNotificationRequestContent{}

// UpdateNotificationRequestContent struct for UpdateNotificationRequestContent
type UpdateNotificationRequestContent struct {
	// Service ID - must be sent as a string
	ServiceId string `json:"service_id"`
	// Notification ID to update
	NotificationId int32 `json:"notification_id"`
	// Name/title for the notification
	Name *string `json:"name,omitempty"`
	Status *NotificationStatus `json:"status,omitempty"`
	// Notification interval in minutes (must be > 0)
	NotificationInterval *int32 `json:"notification_interval,omitempty"`
	// Data timeframe in minutes (must be > 0)
	DataTimeframe *int32 `json:"data_timeframe,omitempty"`
	// Whether all thresholds must be exceeded (true) or any one (false)
	ExceedAll *bool `json:"exceed_all,omitempty"`
	// Email addresses for notifications (comma-separated string or array)
	EmailAddress []string `json:"email_address,omitempty"`
	// CPU usage threshold percentage (0-100)
	CpuUsage *int32 `json:"cpu_usage,omitempty"`
	// Memory usage threshold percentage (0-100)
	MemoryUsage *int32 `json:"memory_usage,omitempty"`
	// Network traffic threshold percentage (0-100)
	NetworkTraffic *int32 `json:"network_traffic,omitempty"`
	// Disk read threshold percentage (0-100)
	DiskRead *int32 `json:"disk_read,omitempty"`
	// Disk write threshold percentage (0-100)
	DiskWrite *int32 `json:"disk_write,omitempty"`
}

type _UpdateNotificationRequestContent UpdateNotificationRequestContent

// NewUpdateNotificationRequestContent instantiates a new UpdateNotificationRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNotificationRequestContent(serviceId string, notificationId int32) *UpdateNotificationRequestContent {
	this := UpdateNotificationRequestContent{}
	this.ServiceId = serviceId
	this.NotificationId = notificationId
	return &this
}

// NewUpdateNotificationRequestContentWithDefaults instantiates a new UpdateNotificationRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNotificationRequestContentWithDefaults() *UpdateNotificationRequestContent {
	this := UpdateNotificationRequestContent{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *UpdateNotificationRequestContent) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *UpdateNotificationRequestContent) SetServiceId(v string) {
	o.ServiceId = v
}

// GetNotificationId returns the NotificationId field value
func (o *UpdateNotificationRequestContent) GetNotificationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NotificationId
}

// GetNotificationIdOk returns a tuple with the NotificationId field value
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetNotificationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotificationId, true
}

// SetNotificationId sets field value
func (o *UpdateNotificationRequestContent) SetNotificationId(v int32) {
	o.NotificationId = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateNotificationRequestContent) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateNotificationRequestContent) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateNotificationRequestContent) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UpdateNotificationRequestContent) GetStatus() NotificationStatus {
	if o == nil || IsNil(o.Status) {
		var ret NotificationStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetStatusOk() (*NotificationStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UpdateNotificationRequestContent) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NotificationStatus and assigns it to the Status field.
func (o *UpdateNotificationRequestContent) SetStatus(v NotificationStatus) {
	o.Status = &v
}

// GetNotificationInterval returns the NotificationInterval field value if set, zero value otherwise.
func (o *UpdateNotificationRequestContent) GetNotificationInterval() int32 {
	if o == nil || IsNil(o.NotificationInterval) {
		var ret int32
		return ret
	}
	return *o.NotificationInterval
}

// GetNotificationIntervalOk returns a tuple with the NotificationInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetNotificationIntervalOk() (*int32, bool) {
	if o == nil || IsNil(o.NotificationInterval) {
		return nil, false
	}
	return o.NotificationInterval, true
}

// HasNotificationInterval returns a boolean if a field has been set.
func (o *UpdateNotificationRequestContent) HasNotificationInterval() bool {
	if o != nil && !IsNil(o.NotificationInterval) {
		return true
	}

	return false
}

// SetNotificationInterval gets a reference to the given int32 and assigns it to the NotificationInterval field.
func (o *UpdateNotificationRequestContent) SetNotificationInterval(v int32) {
	o.NotificationInterval = &v
}

// GetDataTimeframe returns the DataTimeframe field value if set, zero value otherwise.
func (o *UpdateNotificationRequestContent) GetDataTimeframe() int32 {
	if o == nil || IsNil(o.DataTimeframe) {
		var ret int32
		return ret
	}
	return *o.DataTimeframe
}

// GetDataTimeframeOk returns a tuple with the DataTimeframe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetDataTimeframeOk() (*int32, bool) {
	if o == nil || IsNil(o.DataTimeframe) {
		return nil, false
	}
	return o.DataTimeframe, true
}

// HasDataTimeframe returns a boolean if a field has been set.
func (o *UpdateNotificationRequestContent) HasDataTimeframe() bool {
	if o != nil && !IsNil(o.DataTimeframe) {
		return true
	}

	return false
}

// SetDataTimeframe gets a reference to the given int32 and assigns it to the DataTimeframe field.
func (o *UpdateNotificationRequestContent) SetDataTimeframe(v int32) {
	o.DataTimeframe = &v
}

// GetExceedAll returns the ExceedAll field value if set, zero value otherwise.
func (o *UpdateNotificationRequestContent) GetExceedAll() bool {
	if o == nil || IsNil(o.ExceedAll) {
		var ret bool
		return ret
	}
	return *o.ExceedAll
}

// GetExceedAllOk returns a tuple with the ExceedAll field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetExceedAllOk() (*bool, bool) {
	if o == nil || IsNil(o.ExceedAll) {
		return nil, false
	}
	return o.ExceedAll, true
}

// HasExceedAll returns a boolean if a field has been set.
func (o *UpdateNotificationRequestContent) HasExceedAll() bool {
	if o != nil && !IsNil(o.ExceedAll) {
		return true
	}

	return false
}

// SetExceedAll gets a reference to the given bool and assigns it to the ExceedAll field.
func (o *UpdateNotificationRequestContent) SetExceedAll(v bool) {
	o.ExceedAll = &v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise.
func (o *UpdateNotificationRequestContent) GetEmailAddress() []string {
	if o == nil || IsNil(o.EmailAddress) {
		var ret []string
		return ret
	}
	return o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetEmailAddressOk() ([]string, bool) {
	if o == nil || IsNil(o.EmailAddress) {
		return nil, false
	}
	return o.EmailAddress, true
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *UpdateNotificationRequestContent) HasEmailAddress() bool {
	if o != nil && !IsNil(o.EmailAddress) {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given []string and assigns it to the EmailAddress field.
func (o *UpdateNotificationRequestContent) SetEmailAddress(v []string) {
	o.EmailAddress = v
}

// GetCpuUsage returns the CpuUsage field value if set, zero value otherwise.
func (o *UpdateNotificationRequestContent) GetCpuUsage() int32 {
	if o == nil || IsNil(o.CpuUsage) {
		var ret int32
		return ret
	}
	return *o.CpuUsage
}

// GetCpuUsageOk returns a tuple with the CpuUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetCpuUsageOk() (*int32, bool) {
	if o == nil || IsNil(o.CpuUsage) {
		return nil, false
	}
	return o.CpuUsage, true
}

// HasCpuUsage returns a boolean if a field has been set.
func (o *UpdateNotificationRequestContent) HasCpuUsage() bool {
	if o != nil && !IsNil(o.CpuUsage) {
		return true
	}

	return false
}

// SetCpuUsage gets a reference to the given int32 and assigns it to the CpuUsage field.
func (o *UpdateNotificationRequestContent) SetCpuUsage(v int32) {
	o.CpuUsage = &v
}

// GetMemoryUsage returns the MemoryUsage field value if set, zero value otherwise.
func (o *UpdateNotificationRequestContent) GetMemoryUsage() int32 {
	if o == nil || IsNil(o.MemoryUsage) {
		var ret int32
		return ret
	}
	return *o.MemoryUsage
}

// GetMemoryUsageOk returns a tuple with the MemoryUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetMemoryUsageOk() (*int32, bool) {
	if o == nil || IsNil(o.MemoryUsage) {
		return nil, false
	}
	return o.MemoryUsage, true
}

// HasMemoryUsage returns a boolean if a field has been set.
func (o *UpdateNotificationRequestContent) HasMemoryUsage() bool {
	if o != nil && !IsNil(o.MemoryUsage) {
		return true
	}

	return false
}

// SetMemoryUsage gets a reference to the given int32 and assigns it to the MemoryUsage field.
func (o *UpdateNotificationRequestContent) SetMemoryUsage(v int32) {
	o.MemoryUsage = &v
}

// GetNetworkTraffic returns the NetworkTraffic field value if set, zero value otherwise.
func (o *UpdateNotificationRequestContent) GetNetworkTraffic() int32 {
	if o == nil || IsNil(o.NetworkTraffic) {
		var ret int32
		return ret
	}
	return *o.NetworkTraffic
}

// GetNetworkTrafficOk returns a tuple with the NetworkTraffic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetNetworkTrafficOk() (*int32, bool) {
	if o == nil || IsNil(o.NetworkTraffic) {
		return nil, false
	}
	return o.NetworkTraffic, true
}

// HasNetworkTraffic returns a boolean if a field has been set.
func (o *UpdateNotificationRequestContent) HasNetworkTraffic() bool {
	if o != nil && !IsNil(o.NetworkTraffic) {
		return true
	}

	return false
}

// SetNetworkTraffic gets a reference to the given int32 and assigns it to the NetworkTraffic field.
func (o *UpdateNotificationRequestContent) SetNetworkTraffic(v int32) {
	o.NetworkTraffic = &v
}

// GetDiskRead returns the DiskRead field value if set, zero value otherwise.
func (o *UpdateNotificationRequestContent) GetDiskRead() int32 {
	if o == nil || IsNil(o.DiskRead) {
		var ret int32
		return ret
	}
	return *o.DiskRead
}

// GetDiskReadOk returns a tuple with the DiskRead field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetDiskReadOk() (*int32, bool) {
	if o == nil || IsNil(o.DiskRead) {
		return nil, false
	}
	return o.DiskRead, true
}

// HasDiskRead returns a boolean if a field has been set.
func (o *UpdateNotificationRequestContent) HasDiskRead() bool {
	if o != nil && !IsNil(o.DiskRead) {
		return true
	}

	return false
}

// SetDiskRead gets a reference to the given int32 and assigns it to the DiskRead field.
func (o *UpdateNotificationRequestContent) SetDiskRead(v int32) {
	o.DiskRead = &v
}

// GetDiskWrite returns the DiskWrite field value if set, zero value otherwise.
func (o *UpdateNotificationRequestContent) GetDiskWrite() int32 {
	if o == nil || IsNil(o.DiskWrite) {
		var ret int32
		return ret
	}
	return *o.DiskWrite
}

// GetDiskWriteOk returns a tuple with the DiskWrite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRequestContent) GetDiskWriteOk() (*int32, bool) {
	if o == nil || IsNil(o.DiskWrite) {
		return nil, false
	}
	return o.DiskWrite, true
}

// HasDiskWrite returns a boolean if a field has been set.
func (o *UpdateNotificationRequestContent) HasDiskWrite() bool {
	if o != nil && !IsNil(o.DiskWrite) {
		return true
	}

	return false
}

// SetDiskWrite gets a reference to the given int32 and assigns it to the DiskWrite field.
func (o *UpdateNotificationRequestContent) SetDiskWrite(v int32) {
	o.DiskWrite = &v
}

func (o UpdateNotificationRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNotificationRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	toSerialize["notification_id"] = o.NotificationId
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.NotificationInterval) {
		toSerialize["notification_interval"] = o.NotificationInterval
	}
	if !IsNil(o.DataTimeframe) {
		toSerialize["data_timeframe"] = o.DataTimeframe
	}
	if !IsNil(o.ExceedAll) {
		toSerialize["exceed_all"] = o.ExceedAll
	}
	if !IsNil(o.EmailAddress) {
		toSerialize["email_address"] = o.EmailAddress
	}
	if !IsNil(o.CpuUsage) {
		toSerialize["cpu_usage"] = o.CpuUsage
	}
	if !IsNil(o.MemoryUsage) {
		toSerialize["memory_usage"] = o.MemoryUsage
	}
	if !IsNil(o.NetworkTraffic) {
		toSerialize["network_traffic"] = o.NetworkTraffic
	}
	if !IsNil(o.DiskRead) {
		toSerialize["disk_read"] = o.DiskRead
	}
	if !IsNil(o.DiskWrite) {
		toSerialize["disk_write"] = o.DiskWrite
	}
	return toSerialize, nil
}

func (o *UpdateNotificationRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
		"notification_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateNotificationRequestContent := _UpdateNotificationRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateNotificationRequestContent)

	if err != nil {
		return err
	}

	*o = UpdateNotificationRequestContent(varUpdateNotificationRequestContent)

	return err
}

type NullableUpdateNotificationRequestContent struct {
	value *UpdateNotificationRequestContent
	isSet bool
}

func (v NullableUpdateNotificationRequestContent) Get() *UpdateNotificationRequestContent {
	return v.value
}

func (v *NullableUpdateNotificationRequestContent) Set(val *UpdateNotificationRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNotificationRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNotificationRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNotificationRequestContent(val *UpdateNotificationRequestContent) *NullableUpdateNotificationRequestContent {
	return &NullableUpdateNotificationRequestContent{value: val, isSet: true}
}

func (v NullableUpdateNotificationRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNotificationRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


