/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BackupCreationInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupCreationInfo{}

// BackupCreationInfo Information about an ongoing backup creation process
type BackupCreationInfo struct {
	// Backup creation task ID
	Id int32 `json:"id"`
	// Status of the backup creation
	Status string `json:"status"`
	// Status message
	Message string `json:"message"`
	// Timestamp when backup creation started
	CreatedAt string `json:"created_at"`
	// Timestamp when backup creation was last updated
	UpdatedAt string `json:"updated_at"`
}

type _BackupCreationInfo BackupCreationInfo

// NewBackupCreationInfo instantiates a new BackupCreationInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupCreationInfo(id int32, status string, message string, createdAt string, updatedAt string) *BackupCreationInfo {
	this := BackupCreationInfo{}
	this.Id = id
	this.Status = status
	this.Message = message
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewBackupCreationInfoWithDefaults instantiates a new BackupCreationInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupCreationInfoWithDefaults() *BackupCreationInfo {
	this := BackupCreationInfo{}
	return &this
}

// GetId returns the Id field value
func (o *BackupCreationInfo) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BackupCreationInfo) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BackupCreationInfo) SetId(v int32) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *BackupCreationInfo) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *BackupCreationInfo) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *BackupCreationInfo) SetStatus(v string) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *BackupCreationInfo) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *BackupCreationInfo) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *BackupCreationInfo) SetMessage(v string) {
	o.Message = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *BackupCreationInfo) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *BackupCreationInfo) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *BackupCreationInfo) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *BackupCreationInfo) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *BackupCreationInfo) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *BackupCreationInfo) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o BackupCreationInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupCreationInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *BackupCreationInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"message",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackupCreationInfo := _BackupCreationInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackupCreationInfo)

	if err != nil {
		return err
	}

	*o = BackupCreationInfo(varBackupCreationInfo)

	return err
}

type NullableBackupCreationInfo struct {
	value *BackupCreationInfo
	isSet bool
}

func (v NullableBackupCreationInfo) Get() *BackupCreationInfo {
	return v.value
}

func (v *NullableBackupCreationInfo) Set(val *BackupCreationInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupCreationInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupCreationInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupCreationInfo(val *BackupCreationInfo) *NullableBackupCreationInfo {
	return &NullableBackupCreationInfo{value: val, isSet: true}
}

func (v NullableBackupCreationInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupCreationInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


