/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateSnapshotJobRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSnapshotJobRequestContent{}

// UpdateSnapshotJobRequestContent struct for UpdateSnapshotJobRequestContent
type UpdateSnapshotJobRequestContent struct {
	// Service ID - must be sent as a string
	ServiceId string `json:"service_id"`
	// Snapshot job ID to update
	JobId string `json:"job_id"`
	// New name for the snapshot job
	Name *string `json:"name,omitempty"`
	// New description for the snapshot job
	Description *string `json:"description,omitempty"`
	// Whether to include VM state in the snapshot
	Vmstate *bool `json:"vmstate,omitempty"`
	Period *SnapshotJobPeriod `json:"period,omitempty"`
	// For hourly jobs: run every N hours (e.g. 6 = every 6 hours)
	RunEvery *int32 `json:"run_every,omitempty"`
	// For daily jobs: days of week when the job should run
	Days []DayOfWeek `json:"days,omitempty"`
	// For daily jobs: start time in HH:MM format (e.g. '02:30')
	StartTime *string `json:"start_time,omitempty" validate:"regexp=^([01]?[0-9]|2[0-3]):[0-5][0-9]$"`
}

type _UpdateSnapshotJobRequestContent UpdateSnapshotJobRequestContent

// NewUpdateSnapshotJobRequestContent instantiates a new UpdateSnapshotJobRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSnapshotJobRequestContent(serviceId string, jobId string) *UpdateSnapshotJobRequestContent {
	this := UpdateSnapshotJobRequestContent{}
	this.ServiceId = serviceId
	this.JobId = jobId
	return &this
}

// NewUpdateSnapshotJobRequestContentWithDefaults instantiates a new UpdateSnapshotJobRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSnapshotJobRequestContentWithDefaults() *UpdateSnapshotJobRequestContent {
	this := UpdateSnapshotJobRequestContent{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *UpdateSnapshotJobRequestContent) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *UpdateSnapshotJobRequestContent) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *UpdateSnapshotJobRequestContent) SetServiceId(v string) {
	o.ServiceId = v
}

// GetJobId returns the JobId field value
func (o *UpdateSnapshotJobRequestContent) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *UpdateSnapshotJobRequestContent) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *UpdateSnapshotJobRequestContent) SetJobId(v string) {
	o.JobId = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateSnapshotJobRequestContent) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSnapshotJobRequestContent) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateSnapshotJobRequestContent) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateSnapshotJobRequestContent) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateSnapshotJobRequestContent) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSnapshotJobRequestContent) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateSnapshotJobRequestContent) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateSnapshotJobRequestContent) SetDescription(v string) {
	o.Description = &v
}

// GetVmstate returns the Vmstate field value if set, zero value otherwise.
func (o *UpdateSnapshotJobRequestContent) GetVmstate() bool {
	if o == nil || IsNil(o.Vmstate) {
		var ret bool
		return ret
	}
	return *o.Vmstate
}

// GetVmstateOk returns a tuple with the Vmstate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSnapshotJobRequestContent) GetVmstateOk() (*bool, bool) {
	if o == nil || IsNil(o.Vmstate) {
		return nil, false
	}
	return o.Vmstate, true
}

// HasVmstate returns a boolean if a field has been set.
func (o *UpdateSnapshotJobRequestContent) HasVmstate() bool {
	if o != nil && !IsNil(o.Vmstate) {
		return true
	}

	return false
}

// SetVmstate gets a reference to the given bool and assigns it to the Vmstate field.
func (o *UpdateSnapshotJobRequestContent) SetVmstate(v bool) {
	o.Vmstate = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *UpdateSnapshotJobRequestContent) GetPeriod() SnapshotJobPeriod {
	if o == nil || IsNil(o.Period) {
		var ret SnapshotJobPeriod
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSnapshotJobRequestContent) GetPeriodOk() (*SnapshotJobPeriod, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *UpdateSnapshotJobRequestContent) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given SnapshotJobPeriod and assigns it to the Period field.
func (o *UpdateSnapshotJobRequestContent) SetPeriod(v SnapshotJobPeriod) {
	o.Period = &v
}

// GetRunEvery returns the RunEvery field value if set, zero value otherwise.
func (o *UpdateSnapshotJobRequestContent) GetRunEvery() int32 {
	if o == nil || IsNil(o.RunEvery) {
		var ret int32
		return ret
	}
	return *o.RunEvery
}

// GetRunEveryOk returns a tuple with the RunEvery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSnapshotJobRequestContent) GetRunEveryOk() (*int32, bool) {
	if o == nil || IsNil(o.RunEvery) {
		return nil, false
	}
	return o.RunEvery, true
}

// HasRunEvery returns a boolean if a field has been set.
func (o *UpdateSnapshotJobRequestContent) HasRunEvery() bool {
	if o != nil && !IsNil(o.RunEvery) {
		return true
	}

	return false
}

// SetRunEvery gets a reference to the given int32 and assigns it to the RunEvery field.
func (o *UpdateSnapshotJobRequestContent) SetRunEvery(v int32) {
	o.RunEvery = &v
}

// GetDays returns the Days field value if set, zero value otherwise.
func (o *UpdateSnapshotJobRequestContent) GetDays() []DayOfWeek {
	if o == nil || IsNil(o.Days) {
		var ret []DayOfWeek
		return ret
	}
	return o.Days
}

// GetDaysOk returns a tuple with the Days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSnapshotJobRequestContent) GetDaysOk() ([]DayOfWeek, bool) {
	if o == nil || IsNil(o.Days) {
		return nil, false
	}
	return o.Days, true
}

// HasDays returns a boolean if a field has been set.
func (o *UpdateSnapshotJobRequestContent) HasDays() bool {
	if o != nil && !IsNil(o.Days) {
		return true
	}

	return false
}

// SetDays gets a reference to the given []DayOfWeek and assigns it to the Days field.
func (o *UpdateSnapshotJobRequestContent) SetDays(v []DayOfWeek) {
	o.Days = v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *UpdateSnapshotJobRequestContent) GetStartTime() string {
	if o == nil || IsNil(o.StartTime) {
		var ret string
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSnapshotJobRequestContent) GetStartTimeOk() (*string, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *UpdateSnapshotJobRequestContent) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given string and assigns it to the StartTime field.
func (o *UpdateSnapshotJobRequestContent) SetStartTime(v string) {
	o.StartTime = &v
}

func (o UpdateSnapshotJobRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSnapshotJobRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	toSerialize["job_id"] = o.JobId
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Vmstate) {
		toSerialize["vmstate"] = o.Vmstate
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.RunEvery) {
		toSerialize["run_every"] = o.RunEvery
	}
	if !IsNil(o.Days) {
		toSerialize["days"] = o.Days
	}
	if !IsNil(o.StartTime) {
		toSerialize["start_time"] = o.StartTime
	}
	return toSerialize, nil
}

func (o *UpdateSnapshotJobRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
		"job_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSnapshotJobRequestContent := _UpdateSnapshotJobRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateSnapshotJobRequestContent)

	if err != nil {
		return err
	}

	*o = UpdateSnapshotJobRequestContent(varUpdateSnapshotJobRequestContent)

	return err
}

type NullableUpdateSnapshotJobRequestContent struct {
	value *UpdateSnapshotJobRequestContent
	isSet bool
}

func (v NullableUpdateSnapshotJobRequestContent) Get() *UpdateSnapshotJobRequestContent {
	return v.value
}

func (v *NullableUpdateSnapshotJobRequestContent) Set(val *UpdateSnapshotJobRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSnapshotJobRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSnapshotJobRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSnapshotJobRequestContent(val *UpdateSnapshotJobRequestContent) *NullableUpdateSnapshotJobRequestContent {
	return &NullableUpdateSnapshotJobRequestContent{value: val, isSet: true}
}

func (v NullableUpdateSnapshotJobRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSnapshotJobRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


