/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValidatePricingRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidatePricingRequestContent{}

// ValidatePricingRequestContent struct for ValidatePricingRequestContent
type ValidatePricingRequestContent struct {
	// Optional promotional code to apply
	Promo *string `json:"promo,omitempty"`
	// List of products to validate pricing for
	Products []ValidatePricingProduct `json:"products"`
}

type _ValidatePricingRequestContent ValidatePricingRequestContent

// NewValidatePricingRequestContent instantiates a new ValidatePricingRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidatePricingRequestContent(products []ValidatePricingProduct) *ValidatePricingRequestContent {
	this := ValidatePricingRequestContent{}
	this.Products = products
	return &this
}

// NewValidatePricingRequestContentWithDefaults instantiates a new ValidatePricingRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidatePricingRequestContentWithDefaults() *ValidatePricingRequestContent {
	this := ValidatePricingRequestContent{}
	return &this
}

// GetPromo returns the Promo field value if set, zero value otherwise.
func (o *ValidatePricingRequestContent) GetPromo() string {
	if o == nil || IsNil(o.Promo) {
		var ret string
		return ret
	}
	return *o.Promo
}

// GetPromoOk returns a tuple with the Promo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatePricingRequestContent) GetPromoOk() (*string, bool) {
	if o == nil || IsNil(o.Promo) {
		return nil, false
	}
	return o.Promo, true
}

// HasPromo returns a boolean if a field has been set.
func (o *ValidatePricingRequestContent) HasPromo() bool {
	if o != nil && !IsNil(o.Promo) {
		return true
	}

	return false
}

// SetPromo gets a reference to the given string and assigns it to the Promo field.
func (o *ValidatePricingRequestContent) SetPromo(v string) {
	o.Promo = &v
}

// GetProducts returns the Products field value
func (o *ValidatePricingRequestContent) GetProducts() []ValidatePricingProduct {
	if o == nil {
		var ret []ValidatePricingProduct
		return ret
	}

	return o.Products
}

// GetProductsOk returns a tuple with the Products field value
// and a boolean to check if the value has been set.
func (o *ValidatePricingRequestContent) GetProductsOk() ([]ValidatePricingProduct, bool) {
	if o == nil {
		return nil, false
	}
	return o.Products, true
}

// SetProducts sets field value
func (o *ValidatePricingRequestContent) SetProducts(v []ValidatePricingProduct) {
	o.Products = v
}

func (o ValidatePricingRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidatePricingRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Promo) {
		toSerialize["promo"] = o.Promo
	}
	toSerialize["products"] = o.Products
	return toSerialize, nil
}

func (o *ValidatePricingRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"products",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidatePricingRequestContent := _ValidatePricingRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidatePricingRequestContent)

	if err != nil {
		return err
	}

	*o = ValidatePricingRequestContent(varValidatePricingRequestContent)

	return err
}

type NullableValidatePricingRequestContent struct {
	value *ValidatePricingRequestContent
	isSet bool
}

func (v NullableValidatePricingRequestContent) Get() *ValidatePricingRequestContent {
	return v.value
}

func (v *NullableValidatePricingRequestContent) Set(val *ValidatePricingRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableValidatePricingRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableValidatePricingRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidatePricingRequestContent(val *ValidatePricingRequestContent) *NullableValidatePricingRequestContent {
	return &NullableValidatePricingRequestContent{value: val, isSet: true}
}

func (v NullableValidatePricingRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidatePricingRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


