/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DnsRecordMutationData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DnsRecordMutationData{}

// DnsRecordMutationData struct for DnsRecordMutationData
type DnsRecordMutationData struct {
	Message string `json:"message"`
	// Updated DNS records when returned by upstream
	Records []DnsRecordInfo `json:"records,omitempty"`
}

type _DnsRecordMutationData DnsRecordMutationData

// NewDnsRecordMutationData instantiates a new DnsRecordMutationData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnsRecordMutationData(message string) *DnsRecordMutationData {
	this := DnsRecordMutationData{}
	this.Message = message
	return &this
}

// NewDnsRecordMutationDataWithDefaults instantiates a new DnsRecordMutationData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnsRecordMutationDataWithDefaults() *DnsRecordMutationData {
	this := DnsRecordMutationData{}
	return &this
}

// GetMessage returns the Message field value
func (o *DnsRecordMutationData) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *DnsRecordMutationData) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *DnsRecordMutationData) SetMessage(v string) {
	o.Message = v
}

// GetRecords returns the Records field value if set, zero value otherwise.
func (o *DnsRecordMutationData) GetRecords() []DnsRecordInfo {
	if o == nil || IsNil(o.Records) {
		var ret []DnsRecordInfo
		return ret
	}
	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsRecordMutationData) GetRecordsOk() ([]DnsRecordInfo, bool) {
	if o == nil || IsNil(o.Records) {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *DnsRecordMutationData) HasRecords() bool {
	if o != nil && !IsNil(o.Records) {
		return true
	}

	return false
}

// SetRecords gets a reference to the given []DnsRecordInfo and assigns it to the Records field.
func (o *DnsRecordMutationData) SetRecords(v []DnsRecordInfo) {
	o.Records = v
}

func (o DnsRecordMutationData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DnsRecordMutationData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	if !IsNil(o.Records) {
		toSerialize["records"] = o.Records
	}
	return toSerialize, nil
}

func (o *DnsRecordMutationData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDnsRecordMutationData := _DnsRecordMutationData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDnsRecordMutationData)

	if err != nil {
		return err
	}

	*o = DnsRecordMutationData(varDnsRecordMutationData)

	return err
}

type NullableDnsRecordMutationData struct {
	value *DnsRecordMutationData
	isSet bool
}

func (v NullableDnsRecordMutationData) Get() *DnsRecordMutationData {
	return v.value
}

func (v *NullableDnsRecordMutationData) Set(val *DnsRecordMutationData) {
	v.value = val
	v.isSet = true
}

func (v NullableDnsRecordMutationData) IsSet() bool {
	return v.isSet
}

func (v *NullableDnsRecordMutationData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnsRecordMutationData(val *DnsRecordMutationData) *NullableDnsRecordMutationData {
	return &NullableDnsRecordMutationData{value: val, isSet: true}
}

func (v NullableDnsRecordMutationData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnsRecordMutationData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


