/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetDomainContactsResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDomainContactsResponseContent{}

// GetDomainContactsResponseContent struct for GetDomainContactsResponseContent
type GetDomainContactsResponseContent struct {
	Status OperationStatus `json:"status"`
	Data GetDomainContactsData `json:"data"`
}

type _GetDomainContactsResponseContent GetDomainContactsResponseContent

// NewGetDomainContactsResponseContent instantiates a new GetDomainContactsResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDomainContactsResponseContent(status OperationStatus, data GetDomainContactsData) *GetDomainContactsResponseContent {
	this := GetDomainContactsResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewGetDomainContactsResponseContentWithDefaults instantiates a new GetDomainContactsResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDomainContactsResponseContentWithDefaults() *GetDomainContactsResponseContent {
	this := GetDomainContactsResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetDomainContactsResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetDomainContactsResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetDomainContactsResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *GetDomainContactsResponseContent) GetData() GetDomainContactsData {
	if o == nil {
		var ret GetDomainContactsData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetDomainContactsResponseContent) GetDataOk() (*GetDomainContactsData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetDomainContactsResponseContent) SetData(v GetDomainContactsData) {
	o.Data = v
}

func (o GetDomainContactsResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDomainContactsResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetDomainContactsResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDomainContactsResponseContent := _GetDomainContactsResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetDomainContactsResponseContent)

	if err != nil {
		return err
	}

	*o = GetDomainContactsResponseContent(varGetDomainContactsResponseContent)

	return err
}

type NullableGetDomainContactsResponseContent struct {
	value *GetDomainContactsResponseContent
	isSet bool
}

func (v NullableGetDomainContactsResponseContent) Get() *GetDomainContactsResponseContent {
	return v.value
}

func (v *NullableGetDomainContactsResponseContent) Set(val *GetDomainContactsResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDomainContactsResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDomainContactsResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDomainContactsResponseContent(val *GetDomainContactsResponseContent) *NullableGetDomainContactsResponseContent {
	return &NullableGetDomainContactsResponseContent{value: val, isSet: true}
}

func (v NullableGetDomainContactsResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDomainContactsResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


