/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetPublicSshKeyRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPublicSshKeyRequestContent{}

// GetPublicSshKeyRequestContent struct for GetPublicSshKeyRequestContent
type GetPublicSshKeyRequestContent struct {
	// Service ID - must be sent as a string
	ServiceId string `json:"service_id"`
}

type _GetPublicSshKeyRequestContent GetPublicSshKeyRequestContent

// NewGetPublicSshKeyRequestContent instantiates a new GetPublicSshKeyRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPublicSshKeyRequestContent(serviceId string) *GetPublicSshKeyRequestContent {
	this := GetPublicSshKeyRequestContent{}
	this.ServiceId = serviceId
	return &this
}

// NewGetPublicSshKeyRequestContentWithDefaults instantiates a new GetPublicSshKeyRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPublicSshKeyRequestContentWithDefaults() *GetPublicSshKeyRequestContent {
	this := GetPublicSshKeyRequestContent{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *GetPublicSshKeyRequestContent) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *GetPublicSshKeyRequestContent) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *GetPublicSshKeyRequestContent) SetServiceId(v string) {
	o.ServiceId = v
}

func (o GetPublicSshKeyRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPublicSshKeyRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	return toSerialize, nil
}

func (o *GetPublicSshKeyRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetPublicSshKeyRequestContent := _GetPublicSshKeyRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetPublicSshKeyRequestContent)

	if err != nil {
		return err
	}

	*o = GetPublicSshKeyRequestContent(varGetPublicSshKeyRequestContent)

	return err
}

type NullableGetPublicSshKeyRequestContent struct {
	value *GetPublicSshKeyRequestContent
	isSet bool
}

func (v NullableGetPublicSshKeyRequestContent) Get() *GetPublicSshKeyRequestContent {
	return v.value
}

func (v *NullableGetPublicSshKeyRequestContent) Set(val *GetPublicSshKeyRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPublicSshKeyRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPublicSshKeyRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPublicSshKeyRequestContent(val *GetPublicSshKeyRequestContent) *NullableGetPublicSshKeyRequestContent {
	return &NullableGetPublicSshKeyRequestContent{value: val, isSet: true}
}

func (v NullableGetPublicSshKeyRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPublicSshKeyRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


