/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddDnssecRecordResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddDnssecRecordResponseContent{}

// AddDnssecRecordResponseContent struct for AddDnssecRecordResponseContent
type AddDnssecRecordResponseContent struct {
	Status OperationStatus `json:"status"`
	Data DnssecMutationData `json:"data"`
}

type _AddDnssecRecordResponseContent AddDnssecRecordResponseContent

// NewAddDnssecRecordResponseContent instantiates a new AddDnssecRecordResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddDnssecRecordResponseContent(status OperationStatus, data DnssecMutationData) *AddDnssecRecordResponseContent {
	this := AddDnssecRecordResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewAddDnssecRecordResponseContentWithDefaults instantiates a new AddDnssecRecordResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddDnssecRecordResponseContentWithDefaults() *AddDnssecRecordResponseContent {
	this := AddDnssecRecordResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *AddDnssecRecordResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AddDnssecRecordResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AddDnssecRecordResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *AddDnssecRecordResponseContent) GetData() DnssecMutationData {
	if o == nil {
		var ret DnssecMutationData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AddDnssecRecordResponseContent) GetDataOk() (*DnssecMutationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AddDnssecRecordResponseContent) SetData(v DnssecMutationData) {
	o.Data = v
}

func (o AddDnssecRecordResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddDnssecRecordResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AddDnssecRecordResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddDnssecRecordResponseContent := _AddDnssecRecordResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddDnssecRecordResponseContent)

	if err != nil {
		return err
	}

	*o = AddDnssecRecordResponseContent(varAddDnssecRecordResponseContent)

	return err
}

type NullableAddDnssecRecordResponseContent struct {
	value *AddDnssecRecordResponseContent
	isSet bool
}

func (v NullableAddDnssecRecordResponseContent) Get() *AddDnssecRecordResponseContent {
	return v.value
}

func (v *NullableAddDnssecRecordResponseContent) Set(val *AddDnssecRecordResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableAddDnssecRecordResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableAddDnssecRecordResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddDnssecRecordResponseContent(val *AddDnssecRecordResponseContent) *NullableAddDnssecRecordResponseContent {
	return &NullableAddDnssecRecordResponseContent{value: val, isSet: true}
}

func (v NullableAddDnssecRecordResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddDnssecRecordResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


