/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CatalogueGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogueGroup{}

// CatalogueGroup A product group in the catalogue
type CatalogueGroup struct {
	// Group identifier
	Id int32 `json:"id"`
	// Group display name (e.g. Linux Cloud Servers)
	Name string `json:"name"`
	// Products within this group
	Products []CatalogueProduct `json:"products"`
}

type _CatalogueGroup CatalogueGroup

// NewCatalogueGroup instantiates a new CatalogueGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogueGroup(id int32, name string, products []CatalogueProduct) *CatalogueGroup {
	this := CatalogueGroup{}
	this.Id = id
	this.Name = name
	this.Products = products
	return &this
}

// NewCatalogueGroupWithDefaults instantiates a new CatalogueGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogueGroupWithDefaults() *CatalogueGroup {
	this := CatalogueGroup{}
	return &this
}

// GetId returns the Id field value
func (o *CatalogueGroup) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CatalogueGroup) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CatalogueGroup) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CatalogueGroup) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CatalogueGroup) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CatalogueGroup) SetName(v string) {
	o.Name = v
}

// GetProducts returns the Products field value
func (o *CatalogueGroup) GetProducts() []CatalogueProduct {
	if o == nil {
		var ret []CatalogueProduct
		return ret
	}

	return o.Products
}

// GetProductsOk returns a tuple with the Products field value
// and a boolean to check if the value has been set.
func (o *CatalogueGroup) GetProductsOk() ([]CatalogueProduct, bool) {
	if o == nil {
		return nil, false
	}
	return o.Products, true
}

// SetProducts sets field value
func (o *CatalogueGroup) SetProducts(v []CatalogueProduct) {
	o.Products = v
}

func (o CatalogueGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogueGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["products"] = o.Products
	return toSerialize, nil
}

func (o *CatalogueGroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"products",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogueGroup := _CatalogueGroup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogueGroup)

	if err != nil {
		return err
	}

	*o = CatalogueGroup(varCatalogueGroup)

	return err
}

type NullableCatalogueGroup struct {
	value *CatalogueGroup
	isSet bool
}

func (v NullableCatalogueGroup) Get() *CatalogueGroup {
	return v.value
}

func (v *NullableCatalogueGroup) Set(val *CatalogueGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogueGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogueGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogueGroup(val *CatalogueGroup) *NullableCatalogueGroup {
	return &NullableCatalogueGroup{value: val, isSet: true}
}

func (v NullableCatalogueGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogueGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


