/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SuggestDomainsResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuggestDomainsResponseContent{}

// SuggestDomainsResponseContent struct for SuggestDomainsResponseContent
type SuggestDomainsResponseContent struct {
	Status OperationStatus `json:"status"`
	Data DomainSearchResponseData `json:"data"`
}

type _SuggestDomainsResponseContent SuggestDomainsResponseContent

// NewSuggestDomainsResponseContent instantiates a new SuggestDomainsResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuggestDomainsResponseContent(status OperationStatus, data DomainSearchResponseData) *SuggestDomainsResponseContent {
	this := SuggestDomainsResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewSuggestDomainsResponseContentWithDefaults instantiates a new SuggestDomainsResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuggestDomainsResponseContentWithDefaults() *SuggestDomainsResponseContent {
	this := SuggestDomainsResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *SuggestDomainsResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SuggestDomainsResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SuggestDomainsResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *SuggestDomainsResponseContent) GetData() DomainSearchResponseData {
	if o == nil {
		var ret DomainSearchResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SuggestDomainsResponseContent) GetDataOk() (*DomainSearchResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SuggestDomainsResponseContent) SetData(v DomainSearchResponseData) {
	o.Data = v
}

func (o SuggestDomainsResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuggestDomainsResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SuggestDomainsResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuggestDomainsResponseContent := _SuggestDomainsResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSuggestDomainsResponseContent)

	if err != nil {
		return err
	}

	*o = SuggestDomainsResponseContent(varSuggestDomainsResponseContent)

	return err
}

type NullableSuggestDomainsResponseContent struct {
	value *SuggestDomainsResponseContent
	isSet bool
}

func (v NullableSuggestDomainsResponseContent) Get() *SuggestDomainsResponseContent {
	return v.value
}

func (v *NullableSuggestDomainsResponseContent) Set(val *SuggestDomainsResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableSuggestDomainsResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableSuggestDomainsResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuggestDomainsResponseContent(val *SuggestDomainsResponseContent) *NullableSuggestDomainsResponseContent {
	return &NullableSuggestDomainsResponseContent{value: val, isSet: true}
}

func (v NullableSuggestDomainsResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuggestDomainsResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


