/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
)

// checks if the NoVncConsoleDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NoVncConsoleDetails{}

// NoVncConsoleDetails noVNC console connection details
type NoVncConsoleDetails struct {
	// Redirect URL for the noVNC console
	NovncRedirectUrl *string `json:"novnc_redirect_url,omitempty"`
	// Console connection mode
	Mode *string `json:"mode,omitempty"`
	// WebSocket URL for proxied console access
	WebsocketUrl *string `json:"websocket_url,omitempty"`
	// Password for proxied console access
	Password *string `json:"password,omitempty"`
}

// NewNoVncConsoleDetails instantiates a new NoVncConsoleDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNoVncConsoleDetails() *NoVncConsoleDetails {
	this := NoVncConsoleDetails{}
	return &this
}

// NewNoVncConsoleDetailsWithDefaults instantiates a new NoVncConsoleDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNoVncConsoleDetailsWithDefaults() *NoVncConsoleDetails {
	this := NoVncConsoleDetails{}
	return &this
}

// GetNovncRedirectUrl returns the NovncRedirectUrl field value if set, zero value otherwise.
func (o *NoVncConsoleDetails) GetNovncRedirectUrl() string {
	if o == nil || IsNil(o.NovncRedirectUrl) {
		var ret string
		return ret
	}
	return *o.NovncRedirectUrl
}

// GetNovncRedirectUrlOk returns a tuple with the NovncRedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NoVncConsoleDetails) GetNovncRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.NovncRedirectUrl) {
		return nil, false
	}
	return o.NovncRedirectUrl, true
}

// HasNovncRedirectUrl returns a boolean if a field has been set.
func (o *NoVncConsoleDetails) HasNovncRedirectUrl() bool {
	if o != nil && !IsNil(o.NovncRedirectUrl) {
		return true
	}

	return false
}

// SetNovncRedirectUrl gets a reference to the given string and assigns it to the NovncRedirectUrl field.
func (o *NoVncConsoleDetails) SetNovncRedirectUrl(v string) {
	o.NovncRedirectUrl = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *NoVncConsoleDetails) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NoVncConsoleDetails) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *NoVncConsoleDetails) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *NoVncConsoleDetails) SetMode(v string) {
	o.Mode = &v
}

// GetWebsocketUrl returns the WebsocketUrl field value if set, zero value otherwise.
func (o *NoVncConsoleDetails) GetWebsocketUrl() string {
	if o == nil || IsNil(o.WebsocketUrl) {
		var ret string
		return ret
	}
	return *o.WebsocketUrl
}

// GetWebsocketUrlOk returns a tuple with the WebsocketUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NoVncConsoleDetails) GetWebsocketUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WebsocketUrl) {
		return nil, false
	}
	return o.WebsocketUrl, true
}

// HasWebsocketUrl returns a boolean if a field has been set.
func (o *NoVncConsoleDetails) HasWebsocketUrl() bool {
	if o != nil && !IsNil(o.WebsocketUrl) {
		return true
	}

	return false
}

// SetWebsocketUrl gets a reference to the given string and assigns it to the WebsocketUrl field.
func (o *NoVncConsoleDetails) SetWebsocketUrl(v string) {
	o.WebsocketUrl = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *NoVncConsoleDetails) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NoVncConsoleDetails) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *NoVncConsoleDetails) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *NoVncConsoleDetails) SetPassword(v string) {
	o.Password = &v
}

func (o NoVncConsoleDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NoVncConsoleDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NovncRedirectUrl) {
		toSerialize["novnc_redirect_url"] = o.NovncRedirectUrl
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !IsNil(o.WebsocketUrl) {
		toSerialize["websocket_url"] = o.WebsocketUrl
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableNoVncConsoleDetails struct {
	value *NoVncConsoleDetails
	isSet bool
}

func (v NullableNoVncConsoleDetails) Get() *NoVncConsoleDetails {
	return v.value
}

func (v *NullableNoVncConsoleDetails) Set(val *NoVncConsoleDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableNoVncConsoleDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableNoVncConsoleDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNoVncConsoleDetails(val *NoVncConsoleDetails) *NullableNoVncConsoleDetails {
	return &NullableNoVncConsoleDetails{value: val, isSet: true}
}

func (v NullableNoVncConsoleDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNoVncConsoleDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


