/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RestoreBackupResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestoreBackupResponseContent{}

// RestoreBackupResponseContent struct for RestoreBackupResponseContent
type RestoreBackupResponseContent struct {
	Status OperationStatus `json:"status"`
	Data VpsSimpleActionResponseData `json:"data"`
}

type _RestoreBackupResponseContent RestoreBackupResponseContent

// NewRestoreBackupResponseContent instantiates a new RestoreBackupResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestoreBackupResponseContent(status OperationStatus, data VpsSimpleActionResponseData) *RestoreBackupResponseContent {
	this := RestoreBackupResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewRestoreBackupResponseContentWithDefaults instantiates a new RestoreBackupResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestoreBackupResponseContentWithDefaults() *RestoreBackupResponseContent {
	this := RestoreBackupResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *RestoreBackupResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RestoreBackupResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RestoreBackupResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *RestoreBackupResponseContent) GetData() VpsSimpleActionResponseData {
	if o == nil {
		var ret VpsSimpleActionResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RestoreBackupResponseContent) GetDataOk() (*VpsSimpleActionResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RestoreBackupResponseContent) SetData(v VpsSimpleActionResponseData) {
	o.Data = v
}

func (o RestoreBackupResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestoreBackupResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RestoreBackupResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRestoreBackupResponseContent := _RestoreBackupResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRestoreBackupResponseContent)

	if err != nil {
		return err
	}

	*o = RestoreBackupResponseContent(varRestoreBackupResponseContent)

	return err
}

type NullableRestoreBackupResponseContent struct {
	value *RestoreBackupResponseContent
	isSet bool
}

func (v NullableRestoreBackupResponseContent) Get() *RestoreBackupResponseContent {
	return v.value
}

func (v *NullableRestoreBackupResponseContent) Set(val *RestoreBackupResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableRestoreBackupResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableRestoreBackupResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestoreBackupResponseContent(val *RestoreBackupResponseContent) *NullableRestoreBackupResponseContent {
	return &NullableRestoreBackupResponseContent{value: val, isSet: true}
}

func (v NullableRestoreBackupResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestoreBackupResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


