/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatePowerTaskResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePowerTaskResponseContent{}

// CreatePowerTaskResponseContent struct for CreatePowerTaskResponseContent
type CreatePowerTaskResponseContent struct {
	Status OperationStatus `json:"status"`
	Data PowerTaskCreateResponseData `json:"data"`
}

type _CreatePowerTaskResponseContent CreatePowerTaskResponseContent

// NewCreatePowerTaskResponseContent instantiates a new CreatePowerTaskResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePowerTaskResponseContent(status OperationStatus, data PowerTaskCreateResponseData) *CreatePowerTaskResponseContent {
	this := CreatePowerTaskResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewCreatePowerTaskResponseContentWithDefaults instantiates a new CreatePowerTaskResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePowerTaskResponseContentWithDefaults() *CreatePowerTaskResponseContent {
	this := CreatePowerTaskResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *CreatePowerTaskResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreatePowerTaskResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreatePowerTaskResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *CreatePowerTaskResponseContent) GetData() PowerTaskCreateResponseData {
	if o == nil {
		var ret PowerTaskCreateResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreatePowerTaskResponseContent) GetDataOk() (*PowerTaskCreateResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreatePowerTaskResponseContent) SetData(v PowerTaskCreateResponseData) {
	o.Data = v
}

func (o CreatePowerTaskResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePowerTaskResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreatePowerTaskResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePowerTaskResponseContent := _CreatePowerTaskResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePowerTaskResponseContent)

	if err != nil {
		return err
	}

	*o = CreatePowerTaskResponseContent(varCreatePowerTaskResponseContent)

	return err
}

type NullableCreatePowerTaskResponseContent struct {
	value *CreatePowerTaskResponseContent
	isSet bool
}

func (v NullableCreatePowerTaskResponseContent) Get() *CreatePowerTaskResponseContent {
	return v.value
}

func (v *NullableCreatePowerTaskResponseContent) Set(val *CreatePowerTaskResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePowerTaskResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePowerTaskResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePowerTaskResponseContent(val *CreatePowerTaskResponseContent) *NullableCreatePowerTaskResponseContent {
	return &NullableCreatePowerTaskResponseContent{value: val, isSet: true}
}

func (v NullableCreatePowerTaskResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePowerTaskResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


