/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateSshKeysRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSshKeysRequestContent{}

// UpdateSshKeysRequestContent struct for UpdateSshKeysRequestContent
type UpdateSshKeysRequestContent struct {
	// Service ID - must be sent as a string
	ServiceId string `json:"service_id"`
	// SSH public key in OpenSSH format (must start with ssh-rsa, ssh-dss, ssh-ed25519, or ssh-ecdsa)
	SshKeys string `json:"sshKeys" validate:"regexp=^ssh-(rsa|dss|ed25519|ecdsa)\\\\s+[A-Za-z0-9+\\/]+[=]{0,3}(\\\\s+.+)?$"`
}

type _UpdateSshKeysRequestContent UpdateSshKeysRequestContent

// NewUpdateSshKeysRequestContent instantiates a new UpdateSshKeysRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSshKeysRequestContent(serviceId string, sshKeys string) *UpdateSshKeysRequestContent {
	this := UpdateSshKeysRequestContent{}
	this.ServiceId = serviceId
	this.SshKeys = sshKeys
	return &this
}

// NewUpdateSshKeysRequestContentWithDefaults instantiates a new UpdateSshKeysRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSshKeysRequestContentWithDefaults() *UpdateSshKeysRequestContent {
	this := UpdateSshKeysRequestContent{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *UpdateSshKeysRequestContent) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *UpdateSshKeysRequestContent) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *UpdateSshKeysRequestContent) SetServiceId(v string) {
	o.ServiceId = v
}

// GetSshKeys returns the SshKeys field value
func (o *UpdateSshKeysRequestContent) GetSshKeys() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SshKeys
}

// GetSshKeysOk returns a tuple with the SshKeys field value
// and a boolean to check if the value has been set.
func (o *UpdateSshKeysRequestContent) GetSshKeysOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SshKeys, true
}

// SetSshKeys sets field value
func (o *UpdateSshKeysRequestContent) SetSshKeys(v string) {
	o.SshKeys = v
}

func (o UpdateSshKeysRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSshKeysRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	toSerialize["sshKeys"] = o.SshKeys
	return toSerialize, nil
}

func (o *UpdateSshKeysRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
		"sshKeys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSshKeysRequestContent := _UpdateSshKeysRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateSshKeysRequestContent)

	if err != nil {
		return err
	}

	*o = UpdateSshKeysRequestContent(varUpdateSshKeysRequestContent)

	return err
}

type NullableUpdateSshKeysRequestContent struct {
	value *UpdateSshKeysRequestContent
	isSet bool
}

func (v NullableUpdateSshKeysRequestContent) Get() *UpdateSshKeysRequestContent {
	return v.value
}

func (v *NullableUpdateSshKeysRequestContent) Set(val *UpdateSshKeysRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSshKeysRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSshKeysRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSshKeysRequestContent(val *UpdateSshKeysRequestContent) *NullableUpdateSshKeysRequestContent {
	return &NullableUpdateSshKeysRequestContent{value: val, isSet: true}
}

func (v NullableUpdateSshKeysRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSshKeysRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


