/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteDnssecRecordResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteDnssecRecordResponseContent{}

// DeleteDnssecRecordResponseContent struct for DeleteDnssecRecordResponseContent
type DeleteDnssecRecordResponseContent struct {
	Status OperationStatus `json:"status"`
	Data DnssecMutationData `json:"data"`
}

type _DeleteDnssecRecordResponseContent DeleteDnssecRecordResponseContent

// NewDeleteDnssecRecordResponseContent instantiates a new DeleteDnssecRecordResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteDnssecRecordResponseContent(status OperationStatus, data DnssecMutationData) *DeleteDnssecRecordResponseContent {
	this := DeleteDnssecRecordResponseContent{}
	this.Status = status
	this.Data = data
	return &this
}

// NewDeleteDnssecRecordResponseContentWithDefaults instantiates a new DeleteDnssecRecordResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteDnssecRecordResponseContentWithDefaults() *DeleteDnssecRecordResponseContent {
	this := DeleteDnssecRecordResponseContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *DeleteDnssecRecordResponseContent) GetStatus() OperationStatus {
	if o == nil {
		var ret OperationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DeleteDnssecRecordResponseContent) GetStatusOk() (*OperationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DeleteDnssecRecordResponseContent) SetStatus(v OperationStatus) {
	o.Status = v
}

// GetData returns the Data field value
func (o *DeleteDnssecRecordResponseContent) GetData() DnssecMutationData {
	if o == nil {
		var ret DnssecMutationData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteDnssecRecordResponseContent) GetDataOk() (*DnssecMutationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteDnssecRecordResponseContent) SetData(v DnssecMutationData) {
	o.Data = v
}

func (o DeleteDnssecRecordResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteDnssecRecordResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteDnssecRecordResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteDnssecRecordResponseContent := _DeleteDnssecRecordResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteDnssecRecordResponseContent)

	if err != nil {
		return err
	}

	*o = DeleteDnssecRecordResponseContent(varDeleteDnssecRecordResponseContent)

	return err
}

type NullableDeleteDnssecRecordResponseContent struct {
	value *DeleteDnssecRecordResponseContent
	isSet bool
}

func (v NullableDeleteDnssecRecordResponseContent) Get() *DeleteDnssecRecordResponseContent {
	return v.value
}

func (v *NullableDeleteDnssecRecordResponseContent) Set(val *DeleteDnssecRecordResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteDnssecRecordResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteDnssecRecordResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteDnssecRecordResponseContent(val *DeleteDnssecRecordResponseContent) *NullableDeleteDnssecRecordResponseContent {
	return &NullableDeleteDnssecRecordResponseContent{value: val, isSet: true}
}

func (v NullableDeleteDnssecRecordResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteDnssecRecordResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


