/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EditBackupScheduleRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditBackupScheduleRequestContent{}

// EditBackupScheduleRequestContent struct for EditBackupScheduleRequestContent
type EditBackupScheduleRequestContent struct {
	// Service ID - must be sent as a string
	ServiceId string `json:"service_id"`
	// Backup schedule ID to edit
	ScheduleId string `json:"schedule_id"`
	// Time in HH:MM format (e.g., '03:00'). Hours must be between 00-23, minutes must be between 00-59
	Starttime string `json:"starttime" validate:"regexp=^([01]?[0-9]|2[0-3]):[0-5][0-9]$"`
	// Days of week when backup should run
	Dow []DayOfWeek `json:"dow"`
	Compress CompressionType `json:"compress"`
	Mode BackupModeType `json:"mode"`
	// Email notification setting. Set to true to send notifications to client's email, false or omit to disable
	Mailto *bool `json:"mailto,omitempty"`
}

type _EditBackupScheduleRequestContent EditBackupScheduleRequestContent

// NewEditBackupScheduleRequestContent instantiates a new EditBackupScheduleRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditBackupScheduleRequestContent(serviceId string, scheduleId string, starttime string, dow []DayOfWeek, compress CompressionType, mode BackupModeType) *EditBackupScheduleRequestContent {
	this := EditBackupScheduleRequestContent{}
	this.ServiceId = serviceId
	this.ScheduleId = scheduleId
	this.Starttime = starttime
	this.Dow = dow
	this.Compress = compress
	this.Mode = mode
	return &this
}

// NewEditBackupScheduleRequestContentWithDefaults instantiates a new EditBackupScheduleRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditBackupScheduleRequestContentWithDefaults() *EditBackupScheduleRequestContent {
	this := EditBackupScheduleRequestContent{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *EditBackupScheduleRequestContent) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *EditBackupScheduleRequestContent) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *EditBackupScheduleRequestContent) SetServiceId(v string) {
	o.ServiceId = v
}

// GetScheduleId returns the ScheduleId field value
func (o *EditBackupScheduleRequestContent) GetScheduleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScheduleId
}

// GetScheduleIdOk returns a tuple with the ScheduleId field value
// and a boolean to check if the value has been set.
func (o *EditBackupScheduleRequestContent) GetScheduleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduleId, true
}

// SetScheduleId sets field value
func (o *EditBackupScheduleRequestContent) SetScheduleId(v string) {
	o.ScheduleId = v
}

// GetStarttime returns the Starttime field value
func (o *EditBackupScheduleRequestContent) GetStarttime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Starttime
}

// GetStarttimeOk returns a tuple with the Starttime field value
// and a boolean to check if the value has been set.
func (o *EditBackupScheduleRequestContent) GetStarttimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Starttime, true
}

// SetStarttime sets field value
func (o *EditBackupScheduleRequestContent) SetStarttime(v string) {
	o.Starttime = v
}

// GetDow returns the Dow field value
func (o *EditBackupScheduleRequestContent) GetDow() []DayOfWeek {
	if o == nil {
		var ret []DayOfWeek
		return ret
	}

	return o.Dow
}

// GetDowOk returns a tuple with the Dow field value
// and a boolean to check if the value has been set.
func (o *EditBackupScheduleRequestContent) GetDowOk() ([]DayOfWeek, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dow, true
}

// SetDow sets field value
func (o *EditBackupScheduleRequestContent) SetDow(v []DayOfWeek) {
	o.Dow = v
}

// GetCompress returns the Compress field value
func (o *EditBackupScheduleRequestContent) GetCompress() CompressionType {
	if o == nil {
		var ret CompressionType
		return ret
	}

	return o.Compress
}

// GetCompressOk returns a tuple with the Compress field value
// and a boolean to check if the value has been set.
func (o *EditBackupScheduleRequestContent) GetCompressOk() (*CompressionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Compress, true
}

// SetCompress sets field value
func (o *EditBackupScheduleRequestContent) SetCompress(v CompressionType) {
	o.Compress = v
}

// GetMode returns the Mode field value
func (o *EditBackupScheduleRequestContent) GetMode() BackupModeType {
	if o == nil {
		var ret BackupModeType
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *EditBackupScheduleRequestContent) GetModeOk() (*BackupModeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *EditBackupScheduleRequestContent) SetMode(v BackupModeType) {
	o.Mode = v
}

// GetMailto returns the Mailto field value if set, zero value otherwise.
func (o *EditBackupScheduleRequestContent) GetMailto() bool {
	if o == nil || IsNil(o.Mailto) {
		var ret bool
		return ret
	}
	return *o.Mailto
}

// GetMailtoOk returns a tuple with the Mailto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditBackupScheduleRequestContent) GetMailtoOk() (*bool, bool) {
	if o == nil || IsNil(o.Mailto) {
		return nil, false
	}
	return o.Mailto, true
}

// HasMailto returns a boolean if a field has been set.
func (o *EditBackupScheduleRequestContent) HasMailto() bool {
	if o != nil && !IsNil(o.Mailto) {
		return true
	}

	return false
}

// SetMailto gets a reference to the given bool and assigns it to the Mailto field.
func (o *EditBackupScheduleRequestContent) SetMailto(v bool) {
	o.Mailto = &v
}

func (o EditBackupScheduleRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditBackupScheduleRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	toSerialize["schedule_id"] = o.ScheduleId
	toSerialize["starttime"] = o.Starttime
	toSerialize["dow"] = o.Dow
	toSerialize["compress"] = o.Compress
	toSerialize["mode"] = o.Mode
	if !IsNil(o.Mailto) {
		toSerialize["mailto"] = o.Mailto
	}
	return toSerialize, nil
}

func (o *EditBackupScheduleRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"service_id",
		"schedule_id",
		"starttime",
		"dow",
		"compress",
		"mode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEditBackupScheduleRequestContent := _EditBackupScheduleRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEditBackupScheduleRequestContent)

	if err != nil {
		return err
	}

	*o = EditBackupScheduleRequestContent(varEditBackupScheduleRequestContent)

	return err
}

type NullableEditBackupScheduleRequestContent struct {
	value *EditBackupScheduleRequestContent
	isSet bool
}

func (v NullableEditBackupScheduleRequestContent) Get() *EditBackupScheduleRequestContent {
	return v.value
}

func (v *NullableEditBackupScheduleRequestContent) Set(val *EditBackupScheduleRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableEditBackupScheduleRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableEditBackupScheduleRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditBackupScheduleRequestContent(val *EditBackupScheduleRequestContent) *NullableEditBackupScheduleRequestContent {
	return &NullableEditBackupScheduleRequestContent{value: val, isSet: true}
}

func (v NullableEditBackupScheduleRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditBackupScheduleRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


