/*
HostAfricaApi

HostAfrica API

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListOrdersResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOrdersResponseData{}

// ListOrdersResponseData Top-level data payload for the ListOrders response
type ListOrdersResponseData struct {
	// List of orders for the authenticated user
	Orders []Order `json:"orders"`
}

type _ListOrdersResponseData ListOrdersResponseData

// NewListOrdersResponseData instantiates a new ListOrdersResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOrdersResponseData(orders []Order) *ListOrdersResponseData {
	this := ListOrdersResponseData{}
	this.Orders = orders
	return &this
}

// NewListOrdersResponseDataWithDefaults instantiates a new ListOrdersResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOrdersResponseDataWithDefaults() *ListOrdersResponseData {
	this := ListOrdersResponseData{}
	return &this
}

// GetOrders returns the Orders field value
func (o *ListOrdersResponseData) GetOrders() []Order {
	if o == nil {
		var ret []Order
		return ret
	}

	return o.Orders
}

// GetOrdersOk returns a tuple with the Orders field value
// and a boolean to check if the value has been set.
func (o *ListOrdersResponseData) GetOrdersOk() ([]Order, bool) {
	if o == nil {
		return nil, false
	}
	return o.Orders, true
}

// SetOrders sets field value
func (o *ListOrdersResponseData) SetOrders(v []Order) {
	o.Orders = v
}

func (o ListOrdersResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOrdersResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["orders"] = o.Orders
	return toSerialize, nil
}

func (o *ListOrdersResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"orders",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListOrdersResponseData := _ListOrdersResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListOrdersResponseData)

	if err != nil {
		return err
	}

	*o = ListOrdersResponseData(varListOrdersResponseData)

	return err
}

type NullableListOrdersResponseData struct {
	value *ListOrdersResponseData
	isSet bool
}

func (v NullableListOrdersResponseData) Get() *ListOrdersResponseData {
	return v.value
}

func (v *NullableListOrdersResponseData) Set(val *ListOrdersResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableListOrdersResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableListOrdersResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOrdersResponseData(val *ListOrdersResponseData) *NullableListOrdersResponseData {
	return &NullableListOrdersResponseData{value: val, isSet: true}
}

func (v NullableListOrdersResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOrdersResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


