/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PasswordEncryptionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PasswordEncryptionInfo{}

// PasswordEncryptionInfo Encryption metadata for an RSA-OAEP encrypted password
type PasswordEncryptionInfo struct {
	// Asymmetric encryption algorithm. Always \"RSA-OAEP\".
	Algorithm string `json:"algorithm"`
	// OAEP hash / MGF1 hash function. Always \"SHA-256\".
	Hash string `json:"hash"`
	// RSA modulus size in bits. Always 4096.
	KeySize int32 `json:"keySize"`
	// Encoding of the password ciphertext field. Always \"base64\" (standard alphabet, not URL-safe).
	Encoding string `json:"encoding"`
}

type _PasswordEncryptionInfo PasswordEncryptionInfo

// NewPasswordEncryptionInfo instantiates a new PasswordEncryptionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPasswordEncryptionInfo(algorithm string, hash string, keySize int32, encoding string) *PasswordEncryptionInfo {
	this := PasswordEncryptionInfo{}
	this.Algorithm = algorithm
	this.Hash = hash
	this.KeySize = keySize
	this.Encoding = encoding
	return &this
}

// NewPasswordEncryptionInfoWithDefaults instantiates a new PasswordEncryptionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPasswordEncryptionInfoWithDefaults() *PasswordEncryptionInfo {
	this := PasswordEncryptionInfo{}
	return &this
}

// GetAlgorithm returns the Algorithm field value
func (o *PasswordEncryptionInfo) GetAlgorithm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Algorithm
}

// GetAlgorithmOk returns a tuple with the Algorithm field value
// and a boolean to check if the value has been set.
func (o *PasswordEncryptionInfo) GetAlgorithmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Algorithm, true
}

// SetAlgorithm sets field value
func (o *PasswordEncryptionInfo) SetAlgorithm(v string) {
	o.Algorithm = v
}

// GetHash returns the Hash field value
func (o *PasswordEncryptionInfo) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *PasswordEncryptionInfo) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *PasswordEncryptionInfo) SetHash(v string) {
	o.Hash = v
}

// GetKeySize returns the KeySize field value
func (o *PasswordEncryptionInfo) GetKeySize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.KeySize
}

// GetKeySizeOk returns a tuple with the KeySize field value
// and a boolean to check if the value has been set.
func (o *PasswordEncryptionInfo) GetKeySizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeySize, true
}

// SetKeySize sets field value
func (o *PasswordEncryptionInfo) SetKeySize(v int32) {
	o.KeySize = v
}

// GetEncoding returns the Encoding field value
func (o *PasswordEncryptionInfo) GetEncoding() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Encoding
}

// GetEncodingOk returns a tuple with the Encoding field value
// and a boolean to check if the value has been set.
func (o *PasswordEncryptionInfo) GetEncodingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Encoding, true
}

// SetEncoding sets field value
func (o *PasswordEncryptionInfo) SetEncoding(v string) {
	o.Encoding = v
}

func (o PasswordEncryptionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PasswordEncryptionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["algorithm"] = o.Algorithm
	toSerialize["hash"] = o.Hash
	toSerialize["keySize"] = o.KeySize
	toSerialize["encoding"] = o.Encoding
	return toSerialize, nil
}

func (o *PasswordEncryptionInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"algorithm",
		"hash",
		"keySize",
		"encoding",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPasswordEncryptionInfo := _PasswordEncryptionInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPasswordEncryptionInfo)

	if err != nil {
		return err
	}

	*o = PasswordEncryptionInfo(varPasswordEncryptionInfo)

	return err
}

type NullablePasswordEncryptionInfo struct {
	value *PasswordEncryptionInfo
	isSet bool
}

func (v NullablePasswordEncryptionInfo) Get() *PasswordEncryptionInfo {
	return v.value
}

func (v *NullablePasswordEncryptionInfo) Set(val *PasswordEncryptionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePasswordEncryptionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePasswordEncryptionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePasswordEncryptionInfo(val *PasswordEncryptionInfo) *NullablePasswordEncryptionInfo {
	return &NullablePasswordEncryptionInfo{value: val, isSet: true}
}

func (v NullablePasswordEncryptionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePasswordEncryptionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


