/*
HostAfricaApi

HostAfrica API

API version: 1.1.0 - 2026-07-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hasdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceBackupsResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceBackupsResponseData{}

// ServiceBackupsResponseData Response data for service backups operation
type ServiceBackupsResponseData struct {
	// Status message indicating the result
	Message string `json:"message"`
	// List of backups for the service
	Backups []BackupItem `json:"backups"`
	// Total backup quota (null if unlimited)
	QuotaTotal *float64 `json:"quota_total,omitempty"`
	// Used backup quota
	QuotaUsed float64 `json:"quota_used"`
	// Unit for quota measurements (e.g., GiB)
	QuotaUnit string `json:"quota_unit"`
	// Available compression methods for creating backups
	AvailableCompressMethods []CompressionMethod `json:"available_compress_methods"`
	// Available backup modes
	AvailableModes []BackupMode `json:"available_modes"`
	// Whether a backup is currently being created
	BackupIsCreating bool `json:"backup_is_creating"`
	BackupCreation *BackupCreationInfo `json:"backup_creation,omitempty"`
}

type _ServiceBackupsResponseData ServiceBackupsResponseData

// NewServiceBackupsResponseData instantiates a new ServiceBackupsResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceBackupsResponseData(message string, backups []BackupItem, quotaUsed float64, quotaUnit string, availableCompressMethods []CompressionMethod, availableModes []BackupMode, backupIsCreating bool) *ServiceBackupsResponseData {
	this := ServiceBackupsResponseData{}
	this.Message = message
	this.Backups = backups
	this.QuotaUsed = quotaUsed
	this.QuotaUnit = quotaUnit
	this.AvailableCompressMethods = availableCompressMethods
	this.AvailableModes = availableModes
	this.BackupIsCreating = backupIsCreating
	return &this
}

// NewServiceBackupsResponseDataWithDefaults instantiates a new ServiceBackupsResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceBackupsResponseDataWithDefaults() *ServiceBackupsResponseData {
	this := ServiceBackupsResponseData{}
	return &this
}

// GetMessage returns the Message field value
func (o *ServiceBackupsResponseData) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ServiceBackupsResponseData) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ServiceBackupsResponseData) SetMessage(v string) {
	o.Message = v
}

// GetBackups returns the Backups field value
func (o *ServiceBackupsResponseData) GetBackups() []BackupItem {
	if o == nil {
		var ret []BackupItem
		return ret
	}

	return o.Backups
}

// GetBackupsOk returns a tuple with the Backups field value
// and a boolean to check if the value has been set.
func (o *ServiceBackupsResponseData) GetBackupsOk() ([]BackupItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Backups, true
}

// SetBackups sets field value
func (o *ServiceBackupsResponseData) SetBackups(v []BackupItem) {
	o.Backups = v
}

// GetQuotaTotal returns the QuotaTotal field value if set, zero value otherwise.
func (o *ServiceBackupsResponseData) GetQuotaTotal() float64 {
	if o == nil || IsNil(o.QuotaTotal) {
		var ret float64
		return ret
	}
	return *o.QuotaTotal
}

// GetQuotaTotalOk returns a tuple with the QuotaTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBackupsResponseData) GetQuotaTotalOk() (*float64, bool) {
	if o == nil || IsNil(o.QuotaTotal) {
		return nil, false
	}
	return o.QuotaTotal, true
}

// HasQuotaTotal returns a boolean if a field has been set.
func (o *ServiceBackupsResponseData) HasQuotaTotal() bool {
	if o != nil && !IsNil(o.QuotaTotal) {
		return true
	}

	return false
}

// SetQuotaTotal gets a reference to the given float64 and assigns it to the QuotaTotal field.
func (o *ServiceBackupsResponseData) SetQuotaTotal(v float64) {
	o.QuotaTotal = &v
}

// GetQuotaUsed returns the QuotaUsed field value
func (o *ServiceBackupsResponseData) GetQuotaUsed() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.QuotaUsed
}

// GetQuotaUsedOk returns a tuple with the QuotaUsed field value
// and a boolean to check if the value has been set.
func (o *ServiceBackupsResponseData) GetQuotaUsedOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuotaUsed, true
}

// SetQuotaUsed sets field value
func (o *ServiceBackupsResponseData) SetQuotaUsed(v float64) {
	o.QuotaUsed = v
}

// GetQuotaUnit returns the QuotaUnit field value
func (o *ServiceBackupsResponseData) GetQuotaUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuotaUnit
}

// GetQuotaUnitOk returns a tuple with the QuotaUnit field value
// and a boolean to check if the value has been set.
func (o *ServiceBackupsResponseData) GetQuotaUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuotaUnit, true
}

// SetQuotaUnit sets field value
func (o *ServiceBackupsResponseData) SetQuotaUnit(v string) {
	o.QuotaUnit = v
}

// GetAvailableCompressMethods returns the AvailableCompressMethods field value
func (o *ServiceBackupsResponseData) GetAvailableCompressMethods() []CompressionMethod {
	if o == nil {
		var ret []CompressionMethod
		return ret
	}

	return o.AvailableCompressMethods
}

// GetAvailableCompressMethodsOk returns a tuple with the AvailableCompressMethods field value
// and a boolean to check if the value has been set.
func (o *ServiceBackupsResponseData) GetAvailableCompressMethodsOk() ([]CompressionMethod, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvailableCompressMethods, true
}

// SetAvailableCompressMethods sets field value
func (o *ServiceBackupsResponseData) SetAvailableCompressMethods(v []CompressionMethod) {
	o.AvailableCompressMethods = v
}

// GetAvailableModes returns the AvailableModes field value
func (o *ServiceBackupsResponseData) GetAvailableModes() []BackupMode {
	if o == nil {
		var ret []BackupMode
		return ret
	}

	return o.AvailableModes
}

// GetAvailableModesOk returns a tuple with the AvailableModes field value
// and a boolean to check if the value has been set.
func (o *ServiceBackupsResponseData) GetAvailableModesOk() ([]BackupMode, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvailableModes, true
}

// SetAvailableModes sets field value
func (o *ServiceBackupsResponseData) SetAvailableModes(v []BackupMode) {
	o.AvailableModes = v
}

// GetBackupIsCreating returns the BackupIsCreating field value
func (o *ServiceBackupsResponseData) GetBackupIsCreating() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.BackupIsCreating
}

// GetBackupIsCreatingOk returns a tuple with the BackupIsCreating field value
// and a boolean to check if the value has been set.
func (o *ServiceBackupsResponseData) GetBackupIsCreatingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackupIsCreating, true
}

// SetBackupIsCreating sets field value
func (o *ServiceBackupsResponseData) SetBackupIsCreating(v bool) {
	o.BackupIsCreating = v
}

// GetBackupCreation returns the BackupCreation field value if set, zero value otherwise.
func (o *ServiceBackupsResponseData) GetBackupCreation() BackupCreationInfo {
	if o == nil || IsNil(o.BackupCreation) {
		var ret BackupCreationInfo
		return ret
	}
	return *o.BackupCreation
}

// GetBackupCreationOk returns a tuple with the BackupCreation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBackupsResponseData) GetBackupCreationOk() (*BackupCreationInfo, bool) {
	if o == nil || IsNil(o.BackupCreation) {
		return nil, false
	}
	return o.BackupCreation, true
}

// HasBackupCreation returns a boolean if a field has been set.
func (o *ServiceBackupsResponseData) HasBackupCreation() bool {
	if o != nil && !IsNil(o.BackupCreation) {
		return true
	}

	return false
}

// SetBackupCreation gets a reference to the given BackupCreationInfo and assigns it to the BackupCreation field.
func (o *ServiceBackupsResponseData) SetBackupCreation(v BackupCreationInfo) {
	o.BackupCreation = &v
}

func (o ServiceBackupsResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceBackupsResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["backups"] = o.Backups
	if !IsNil(o.QuotaTotal) {
		toSerialize["quota_total"] = o.QuotaTotal
	}
	toSerialize["quota_used"] = o.QuotaUsed
	toSerialize["quota_unit"] = o.QuotaUnit
	toSerialize["available_compress_methods"] = o.AvailableCompressMethods
	toSerialize["available_modes"] = o.AvailableModes
	toSerialize["backup_is_creating"] = o.BackupIsCreating
	if !IsNil(o.BackupCreation) {
		toSerialize["backup_creation"] = o.BackupCreation
	}
	return toSerialize, nil
}

func (o *ServiceBackupsResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"backups",
		"quota_used",
		"quota_unit",
		"available_compress_methods",
		"available_modes",
		"backup_is_creating",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceBackupsResponseData := _ServiceBackupsResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceBackupsResponseData)

	if err != nil {
		return err
	}

	*o = ServiceBackupsResponseData(varServiceBackupsResponseData)

	return err
}

type NullableServiceBackupsResponseData struct {
	value *ServiceBackupsResponseData
	isSet bool
}

func (v NullableServiceBackupsResponseData) Get() *ServiceBackupsResponseData {
	return v.value
}

func (v *NullableServiceBackupsResponseData) Set(val *ServiceBackupsResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceBackupsResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceBackupsResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceBackupsResponseData(val *ServiceBackupsResponseData) *NullableServiceBackupsResponseData {
	return &NullableServiceBackupsResponseData{value: val, isSet: true}
}

func (v NullableServiceBackupsResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceBackupsResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


